import requests
from bs4 import BeautifulSoup
import re
#The basics
import numpy as np
import pandas as pd

#Get them web sites
import requests

#Make sure slenium works
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import os

#Start the google driver
driver = webdriver.PhantomJS(service_args=['--ssl-protocol=any'])
#For inserting articles into Mongodb
from pymongo import MongoClient
#long string
info_links_2 = ['https://www.infowars.com/comey-grilled-as-feds-seriously-consider-charging-mccabe-in-criminal-referral/',
 'https://www.infowars.com/trump-tees-off-on-fbi-and-doj-for-missing-clinton-russia-document-deadline/',
 'https://www.infowars.com/trump-tweetstorm-when-does-this-witch-hunt-stop/',
 'https://www.infowars.com/roger-stone-john-bolton-is-a-vast-improvement-over-mcmaster-for-security-adviser/',
 'https://www.infowars.com/democratic-party-lawsuit-claims-russia-trump-campaign-and-wikileaks-conspired-to-disrupt-2016-election/',
 'https://www.infowars.com/black-lives-matter-protesters-descend-on-sacramento-block-streets-disrupt-nba-game/',
 'https://www.infowars.com/trump-backed-republican-gubernatorial-candidate-wins-in-california-let-that-sink-in/',
 'https://www.infowars.com/im-on-a-secret-government-mission-says-man-arrested-with-weapons-cache/',
 'https://www.infowars.com/amazon-bars-christians-from-charity-program-but-allows-islamic-groups/',
 'https://www.infowars.com/hillarys-bulge-clinton-hiding-something-under-heavy-coats-and-scarfs/',
 'https://www.infowars.com/republican-senator-says-trump-is-nuts-david-hogg-flips-out-when-bill-oreilly-proves-he-works-for-soros/',
 'https://www.infowars.com/playboy-joins-deletefacebook-movement/',
 'https://www.infowars.com/media-claims-trump-called-immigrants-animals-when-he-was-talking-about-ms-13-gang-members/',
 'https://www.infowars.com/genocide-armenian-americans-await-trumps-wording-on-early-20th-century-mass-killings/',
 'https://www.infowars.com/mad-maxine-waters-kanye-west-talking-out-of-turn/',
 'https://www.infowars.com/trump-base-revolts-over-signing-of-budget-bill/',
 'https://www.infowars.com/trump-criminal-deep-state-caught-up-in-major-spy-scandal/',
 'https://www.infowars.com/cnn-cuts-interview-after-shooting-victims-brother-accuses-media-of-ruining-lives-forever/',
 'https://www.infowars.com/pompeo-real-progress-in-talks-with-kims-deputy-on-potential-summit/',
 'https://www.infowars.com/jared-kushner-gets-permanent-white-house-security-clearance/',
 'https://www.infowars.com/wp-content/uploads/2018/05/229990_image.jpg',
 'https://www.infowars.com/kill-trump-hang-him-hunt-him-facebook-page-doesnt-violate-facebook-community-standards/',
 'https://www.infowars.com/man-facing-federal-gun-charges-after-court-order-returned-weapons/',
 'https://www.infowars.com/watch-live-will-trump-pardon-himself/#disqus_thread',
 'https://www.infowars.com/shock-taxpayer-cash-laundered-through-somali-daycares-to-fund-terrorism/',
 'https://www.infowars.com/black-guy-walks-into-starbucks-says-racist-immediately-gets-free-coffee/',
 'https://www.infowars.com/exacerbated-frustrated-trump-agrees-to-keep-troops-in-syria-after-pressure-from-pentagon/',
 'https://www.infowars.com/former-president-george-hw-bush-hospitalized-in-maine/',
 'https://www.infowars.com/planned-parenthood-we-need-disney-princess-whos-had-abortion/',
 'https://www.infowars.com/american-who-escaped-al-qaeda-captivity-in-syria-says-the-fbi-under-mueller-and-comey-betrayed-him/',
 'https://www.infowars.com/donald-trump-democrats-rooting-against-united-states-in-north-korea-negotiations/',
 'https://www.infowars.com/nuclear-doomsday-plane-goes-airborne-as-war-fears-grow/',
 'https://www.infowars.com/kent-state-gun-girl-challenges-david-hogg-lets-arm-wrestle/',
 'https://www.infowars.com/trenchcoat-belonging-to-santa-fe-school-shooter-shows-both-communist-and-nazi-symbols/',
 'https://www.infowars.com/revealed-dream-democrat-agenda-includes-reparations/',
 'https://www.infowars.com/video-michigan-union-boss-neglects-mandatory-reporting-of-child-abuse/',
 'https://www.infowars.com/trump-insists-that-if-he-wanted-to-fire-mueller-he-already-would-have/',
 'https://www.infowars.com/fec-records-suggest-clinton-campaign-laundered-84-million/',
 'https://www.infowars.com/rod-rosensteins-wife-a-mystery-woman-of-conflict/#disqus_thread',
 'https://www.infowars.com/members-of-migrant-caravan-stopped-at-us-border-entry-report/',
 'https://www.infowars.com/dennis-prager-slams-nyt-best-seller-list/',
 'https://www.infowars.com/sociologist-less-than-10-percent-of-march-for-our-lives-participants-were-children/',
 'https://www.infowars.com/splc-cashes-in-on-trump-era-controversial-nonprofit-nears-half-billion-in-assets/',
 'https://www.infowars.com/giuliani-whole-country-will-turn-on-mueller-if-he-targets-ivanka/',
 'https://www.infowars.com/nyt-columnist-worries-mueller-investigation-actually-helping-trump/#disqus_thread',
 'https://www.infowars.com/watch-left-wing-protester-spits-on-officer-at-blue-lives-matter-demonstration/',
 'https://www.infowars.com/cartoon-highlights-insanity-of-americas-current-political-climate/',
 'https://www.infowars.com/time-for-msnbcs-joy-reid-to-fess-up/',
 'https://www.infowars.com/dem-lawmaker-we-dont-want-to-confiscate-guns-we-want-to-seize-them/',
 'https://www.infowars.com/number-of-illegal-aliens-granted-california-drivers-licenses-passes-one-million/',
 'https://www.infowars.com/acosta-trumps-supporters-could-run-out-of-anger-begin-to-binge-watch-something-else/',
 'https://www.infowars.com/emboldened-by-march-for-our-lives-far-left-dc-council-considers-lowering-voting-age-to-16/',
 'https://www.infowars.com/hillary-clinton-large-portion-of-us-uneasy-angry-about-women-seeking-power/',
 'https://www.infowars.com/waffle-house-gunman-who-is-at-large-with-a-gun-killed-four-with-an-ar-15-that-was-confiscated-by-the-fbi-in-july/',
 'https://www.infowars.com/audience-at-donald-trump-hispanic-business-event-chant-four-more-years/',
 'https://www.infowars.com/fake-news-wa-post-ny-times-win-pulitzer-prize-for-unearthing-possible-ties-between-trump-and-russia/',
 'https://www.infowars.com/another-gun-stops-a-mass-shooting-proving-the-2nd-amendment-is-the-answer/',
 'https://www.infowars.com/buchanan-smut-night-at-the-press-dinner/',
 'https://www.infowars.com/illegal-alien-accused-of-ramming-motorcyclist-off-the-road-arrested/#disqus_thread',
 'https://www.infowars.com/bump-stock-maker-to-shut-down-website-stop-taking-orders/',
 'https://www.infowars.com/federal-judge-releases-illegal-alien-who-rammed-car-into-daycare-center/',
 'https://www.infowars.com/california-bill-wants-to-drop-washington-lincolns-birthday-and-replace-it-with-communist-holiday/',
 'https://www.infowars.com/broward-coward-scot-peterson-starts-receiving-8702-a-month-pension/',
 'https://www.infowars.com/trump-comey-is-a-weak-and-untruthful-slime-ball/',
 'https://www.infowars.com/cnns-van-jones-admits-liberals-waste-so-much-time-freaking-out-about-trump/#disqus_thread',
 'https://www.infowars.com/trumps-approval-rating-amongst-black-males-doubles-since-kanye-controversy/',
 'https://www.infowars.com/they-loathe-christians-google-refuses-to-recognize-easter/',
 'https://www.infowars.com/congressman-fbi-report-says-andrew-mccabe-lied-four-times-about-media-leaks/',
 'https://www.infowars.com/hannity-digs-up-dirt-on-muellers-past-and-finds-hes-not-so-clean-after-all/',
 'https://www.infowars.com/gop-lawmaker-we-might-need-to-build-a-wall-between-california-and-arizona/',
 'https://www.infowars.com/shock-footage-parkland-gunman-vows-to-shoot-up-school/',
 'https://www.infowars.com/trump-attorney-rudy-giuliani-says-jared-kushner-disposable/',
 'https://www.infowars.com/special-counsel-probing-donations-with-foreign-connections-to-trump-inauguration/',
 'https://www.infowars.com/poll-half-of-republicans-think-media-should-be-described-as-enemy-of-people/#disqus_thread',
 'https://www.infowars.com/metro-area-populations-surge-as-rural-america-shrinks/',
 'https://www.infowars.com/mystery-group-of-wealthy-donors-and-soros-spends-50-million-for-private-trump-russia-investigation/',
 'https://www.infowars.com/veterans-discuss-sessions-and-dirty-doj-over-memorial-day-weekend/#disqus_thread',
 'https://www.infowars.com/judges-death-gives-trump-opportunity-to-overhaul-liberal-9th-circuit-court/',
 'https://www.infowars.com/all-womens-college-asks-profs-not-to-call-students-women/',
 'https://www.infowars.com/trump-expecting-letter-from-kim-jong-un/',
 'https://www.infowars.com/msm-calls-lopsided-7-2-ruling-over-gay-cake-narrow-win/',
 'https://www.infowars.com/mad-maxine-waters-kanye-west-talking-out-of-turn/#disqus_thread',
 'https://www.infowars.com/shock-study-climate-skeptics-more-eco-friendly-than-climate-alarmists/',
 'https://www.infowars.com/stormy-lawyer-time-for-giuliani-to-be-put-out-to-pasture/',
 'https://www.infowars.com/watch-reporter-confronts-bill-clinton-over-lewinsky-metoo-movement/',
 'https://www.infowars.com/alex-jones-responds-to-sinclair-jim-carrey-controversy/',
 'https://www.infowars.com/stossel-the-great-american-tax-ripoff/',
 'https://www.infowars.com/san-diego-county-joins-californias-sanctuary-state-revolt/',
 'https://www.infowars.com/video-the-truth-about-gun-control/',
 'https://www.infowars.com/dershowitz-dems-ignoring-civil-liberties-to-get-devil-trump/',
 'https://www.infowars.com/public-schools-are-no-longer-schools-but-liberal-indoctrination-stations/',
 'https://www.infowars.com/laura-ingraham-taking-next-week-off-amid-feud-with-parkland-student-david-hogg-advertiser-boycott/',
 'https://www.infowars.com/hs-principal-apologizes-for-party-like-its-1776-on-prom-tickets/',
 'https://www.infowars.com/special-counsel-robert-mueller-focusing-sharply-on-links-between-trump-confidant-roger-stone-and-former-campaign-official-rick-gates-sources-say/',
 'https://www.infowars.com/james-comey-creates-deeper-legal-jeopardy-with-cnn-townhall-answer/',
 'https://www.infowars.com/trump-says-hillary-clintons-gaffes-prove-democrats-lost-touch-with-regular-americans/',
 'https://www.infowars.com/rod-rosenstein-to-face-off-with-gop-lawmakers-amid-questions-about-fbi-informant/',
 'https://www.infowars.com/poll-more-americans-than-ever-see-media-as-enemy-of-trump/',
 'https://www.infowars.com/mueller-reportedly-told-trumps-lawyers-the-president-is-not-a-criminal-target-at-this-point/',
 'https://www.infowars.com/triumphant-rep-steve-scalise-returns-to-baseball-diamond/',
 'https://www.infowars.com/blowback-cnn-poll-shows-trump-approval-spikes-amid-stormy-daniels-interview/',
 'https://www.infowars.com/spygate-update-clapper-says-i-have-an-aversion-to-use-of-the-word-spy/',
 'https://www.infowars.com/cnn-reporters-triggered-by-people-getting-their-news-from-youtubers-instead-of-mainstream-media/#disqus_thread',
 'https://www.infowars.com/shocked-cnn-panel-says-trump-is-watching-alex-jones/',
 'https://www.infowars.com/white-house-counters-chinas-orwellian-disinformation-aimed-at-americans/',
 'https://www.infowars.com/dhs-radio-ads-recruit-migrants-from-central-america/',
 'https://www.infowars.com/parkland-survivor-to-gun-control-classmates-dont-use-my-sisters-name-to-push-your-agenda/',
 'https://www.infowars.com/members-of-migrant-caravan-admit-they-want-to-enter-america-for-money/',
 'https://www.infowars.com/roseanne-barr-to-appear-on-joe-rogan-podcast/',
 'https://www.infowars.com/rand-paul-deep-state-is-trying-to-bring-trump-down/',
 'https://www.infowars.com/im-happy-the-witch-is-dead-lefty-trolls-celebrate-barbara-bushs-death-mock-her-as-white-supremacy/',
 'https://www.infowars.com/happy-mothers-day-america-12-million-millennials-still-live-with-their-moms/',
 'https://www.infowars.com/students-call-jefferson-icon-of-white-supremacists/',
 'https://www.infowars.com/wp-content/uploads/2018/05/bill-faithful-768x605.jpg',
 'https://www.infowars.com/trump-to-expel-60-russian-diplomats-from-u-s/',
 'https://www.infowars.com/cnn-analyst-chris-cillizza-posts-deletes-tweet-showing-trump-in-crosshairs/',
 'https://www.infowars.com/trump-rips-correspondents-dinner-filthy-michelle-wolf/',
 'https://www.infowars.com/exclusive-eyewitnesses-to-santa-fe-high-school-shooting-speak-out/',
 'https://www.infowars.com/remington-oldest-us-gunmaker-files-for-bankruptcy/',
 'https://www.infowars.com/liberals-announce-plan-to-crush-normal-americans-in-a-new-civil-war/',
 'https://www.infowars.com/u-s-tests-icbm-ahead-of-trump-kim-summit/',
 'https://www.infowars.com/democrats-want-you-unarmed-when-your-house-is-invaded/',
 'https://www.infowars.com/tucker-carlson-ms-13-is-a-living-reminder-that-the-lefts-position-on-immigration-is-fundamentally-a-lie/',
 'https://www.infowars.com/msnbc-guest-mike-pence-would-put-gay-people-in-concentration-camps-if-he-became-president/',
 'https://www.infowars.com/school-orders-teacher-to-change-shirt-that-had-words-just-pray-on-it/',
 'https://www.infowars.com/rand-paul-warns-trump-haters-at-fbi-still-have-top-secret-security-clearance/',
 'https://www.infowars.com/ny-times-op-ed-repeal-the-second-amendment-to-make-schoolchildren-safer/',
 'https://www.infowars.com/gretchen-carlson-allowing-fatties-to-enter-miss-america-is-part-of-cultural-revolution/',
 'https://www.infowars.com/youtube-shooter-witness-i-didnt-have-a-gun-but-i-wish-i-did/',
 'https://www.infowars.com/dan-bongino-blasts-democrats-for-hating-on-in-god-we-trust/',
 'https://www.infowars.com/gop-gov-candidate-tours-sanctuary-cities-with-deportation-bus/',
 'https://www.infowars.com/man-who-was-deported-3-times-is-facing-child-sexual-assault-charges/',
 'https://www.infowars.com/new-footage-shows-las-vegas-gunman-preparing-for-massacre/',
 'https://www.infowars.com/so-called-prison-bus-for-babies-was-made-under-obama-viral-photo-is-two-years-old/',
 'https://www.infowars.com/trump-tears-into-john-kerry-over-shadow-diplomacy-with-iran/',
 'https://www.infowars.com/homeland-chief-warns-immigrant-caravan-we-will-enforce-the-immigration-laws/',
 'https://www.infowars.com/polls-show-americans-are-growing-increasingly-disinterested-in-muellers-russia-probe/#disqus_thread',
 'https://www.infowars.com/hundreds-of-thousands-rolled-thunder-through-dc-to-honor-fallen-veterans/',
 'https://www.infowars.com/polls-show-americans-are-growing-increasingly-disinterested-in-muellers-russia-probe/',
 'https://www.infowars.com/fox-news-stands-by-ingraham-slams-agenda-driven-intimidation-efforts/',
 'https://www.infowars.com/broward-county-deputies-schedule-no-confidence-vote-for-sheriff-scott-israel/',
 'https://www.infowars.com/boy-scouts-to-remove-word-boy-from-name/',
 'https://www.infowars.com/breaking-news/',
 'https://www.infowars.com/trump-administration-reportedly-to-cut-federal-funding-to-planned-parenthood/',
 'https://www.infowars.com/paul-ryan-comey-a-man-of-integrity-as-far-as-i-know/',
 'https://www.infowars.com/new-us-history-school-textbook-slams-trump-supporters-as-scared-racists/',
 'https://www.infowars.com/protest-signs-admit-real-agenda-behind-march-for-our-lives/',
 'https://www.infowars.com/parkland-school-shooting-survivor-dont-blame-guns-blame-the-cowards-of-broward-county/',
 'https://www.infowars.com/terms-of-service/',
 'https://www.infowars.com/gretchen-carlson-allowing-fatties-to-enter-miss-america-is-part-of-cultural-revolution/#disqus_thread',
 'https://www.infowars.com/schumer-says-no-evidence-of-spy-in-trump-campaign/',
 'https://www.infowars.com/brooklyn-museum-sparks-outrage-after-hiring-white-curator-for-african-art-exhibit/',
 'https://www.infowars.com/trump-the-second-amendment-will-never-be-repealed/',
 'https://www.infowars.com/video-ingraham-and-gorkas-heated-debate-over-syria-strike/',
 'https://www.infowars.com/youtube-allows-video-depiction-of-massacre-to-be-watched-by-children-censors-criticism-of-it/',
 'https://www.infowars.com/cnn-reporters-triggered-by-people-getting-their-news-from-youtubers-instead-of-mainstream-media/',
 'https://www.infowars.com/fbi-spying-on-trump-started-in-london-earlier-than-thought-new-texts-implicate-obama-white-house/',
 'https://www.infowars.com/trump-kanye-gets-it-the-trump-admin-is-good-for-the-black-community/',
 'https://www.infowars.com/florida-judge-rules-ballots-were-illegally-destroyed-in-wasserman-schultz-race/',
 'https://www.infowars.com/arizona-border-ranchers-live-in-fear-as-illegal-immigration-crisis-worsens/',
 'https://www.infowars.com/dershowitz-targeting-trumps-lawyer-should-worry-us-all/',
 'https://www.infowars.com/obama-aide-trumps-cheatin-obama-comment-might-be-racist/',
 'https://www.infowars.com/obamas-join-netflix-to-shape-culture/',
 'https://www.infowars.com/privacy-policy',
 'https://www.infowars.com/wp-content/uploads/2018/05/230061_image.jpg',
 'https://www.infowars.com/john-mccain-reportedly-wants-obama-at-his-funeral-but-not-trump/',
 'https://www.infowars.com/video-students-say-trump-doesnt-deserve-nobel-but-obama-does/',
 'https://www.infowars.com/trump-seals-jfk-documents-until-2021/',
 'https://www.infowars.com/department-of-homeland-security-compiling-database-of-journalists-and-media-influencers/',
 'https://www.infowars.com/dccc-hit-with-ethics-complaint-after-secret-recording-released/',
 'https://www.infowars.com/youtube-hq-shooting-eyewitness-didnt-have-a-gun-on-me-but-wish-i-did/',
 'https://www.infowars.com/gingrich-trump-will-get-reelected-is-changing-americas-future/',
 'https://www.infowars.com/berkeley-blames-conservatives-for-campus-violence-at-free-speech-events/',
 'https://www.infowars.com/political-prisoner-martyg-writes-to-doj-inspector-general/',
 'https://www.infowars.com/parkland-teacher-allegedly-called-pro-gun-jewish-student-the-hitler-type/',
 'https://www.infowars.com/marginalizing-melania/',
 'https://www.infowars.com/gop-pushes-gun-control-in-national-survey/',
 'https://www.infowars.com/devin-nunes-threatens-to-impeach-dojs-rod-rosenstein-and-fbis-chris-wray/',
 'https://www.infowars.com/identity-of-austin-bombing-suspect-released/',
 'https://www.infowars.com/hillary-i-worry-trump-has-harmed-americas-world-leadership/',
 'https://www.infowars.com/how-state-gop-leaders-are-quietly-backing-warren-in-massachusetts/',
 'https://www.infowars.com/trump-nominates-1st-african-american-woman-to-be-marine-brigadier-general/',
 'https://www.infowars.com/texas-arizona-announce-troop-deployments-to-mexico-border/',
 'https://www.infowars.com/obamas-doj-protected-clinton-tried-to-destroy-trump/',
 'https://www.infowars.com/no-amendment-is-absolute-d-c-student-school-walkout-organizer-says-we-must-regulate-the-second-amendment/',
 'https://www.infowars.com/us-south-korea-presidents-to-discuss-threat-to-scrap-trump-kim-summit/',
 'https://www.infowars.com/over-450-caravan-migrants-entered-us/',
 'https://www.infowars.com/secret-fbi-source-for-russia-investigation-met-with-three-trump-advisers-during-campaign/',
 'https://www.infowars.com/report-mccabes-publicist-once-prosecuted-oliver-north/',
 'https://www.infowars.com/never-again-david-hogg-to-release-anti-second-amendment-manifesto/',
 'https://www.infowars.com/nikki-haleys-deputy-ambassador-led-never-trump-movement-launched-zuckerbergs-open-borders-group/',
 'https://www.infowars.com/u-s-north-korea-to-hold-second-day-of-nuclear-talks/',
 'https://www.infowars.com/trump-just-took-a-giant-step-towards-actual-welfare-reform/',
 'https://www.infowars.com/comey-was-being-investigated-for-political-interference-at-time-of-firing/',
 'https://www.infowars.com/cnn-covers-trump-going-on-a-diet-in-ongoing-obsession-with-presidents-weight/',
 'https://www.infowars.com/giuliani-comey-mccabe-should-be-prosecuted/',
 'https://www.infowars.com/jorge-ramos-says-trump-wants-to-make-america-white-again-tuckers-response-embarrasses-him/',
 'https://www.infowars.com/march-for-our-lives-protesters-trash-streets-of-d-c-after-gun-control-march/',
 'https://www.infowars.com/obama-i-would-like-to-create-a-million-young-barack-obamas/',
 'https://www.infowars.com/professor-vows-to-boost-female-students-grades-to-offset-gender-imbalances/#disqus_thread',
 'https://www.infowars.com/big-victory-for-president-trump-commerce-department-puts-u-s-citizenship-question-back-on-census/',
 'https://www.infowars.com/gorka-to-grassroots-trump-is-the-kryptonite-of-political-correctness/',
 'https://www.infowars.com/savage-fbi-agent-refuses-to-investigate-tortured-children/',
 'https://www.infowars.com/youtube-faces-backlash-after-banning-firearm-demo-videos/',
 'https://www.infowars.com/kanye-west-seeks-restraining-order-against-rapper-who-called-on-crips-to-fk-him-up/',
 'https://www.infowars.com/video-msnbc-blames-trump-for-media-taking-his-ms-13-comments-out-of-context/',
 'https://www.infowars.com/roger-stone-corrects-the-record-i-did-not-predict-mueller-will-move-on-me/',
 'https://www.infowars.com/report-dhs-secretary-defies-trump-awards-grants-to-sanctuary-cities/',
 'https://www.infowars.com/miss-america-contestants-will-no-longer-be-judged-on-personal-appearance/',
 'https://www.infowars.com/sarah-sanders-dems-have-to-decide-if-they-love-the-us-more-than-they-hate-trump/',
 'https://www.infowars.com/emma-gonzalez-retweets-message-blaming-white-boys-entitlement-as-cause-of-all-school-shootings/',
 'https://www.infowars.com/grocery-chain-caves-under-david-hoggs-newest-bullying-tactic/',
 'https://www.infowars.com/oklahoma-senate-passes-permit-less-carry-bill/',
 'https://www.infowars.com/democrats-silent-on-highest-ranking-openly-gay-nominee-ever/',
 'https://www.infowars.com/robert-de-niro-ben-stiller-star-in-snl-as-bob-mueller-and-michael-cohen/',
 'https://www.infowars.com/parkland-students-going-on-nationwide-bus-tour-to-register-voters-call-out-nra-donation-recipients/',
 'https://www.infowars.com/abc-news-star-joy-behar-says-kim-jong-un-putin-have-more-sanity-than-trump/',
 'https://www.infowars.com/the-revolutionary-war-started-at-lexington-concord-when-tyrants-tried-to-take-our-firearms-in-1775/',
 'https://www.infowars.com/donald-trump-boasts-about-securing-1-6billion-in-funds-to-build-the-wall-with-mexico/',
 'https://www.infowars.com/miss-america-contestants-will-no-longer-be-judged-on-personal-appearance/#disqus_thread',
 'https://www.infowars.com/gingrich-calls-mueller-investigation-breakdown-of-constitutional-law/',
 'https://www.infowars.com/video-trump-agrees-repealing-second-amendment-would-be-tyranny/',
 'https://www.infowars.com/after-defending-ms-13-murderers-left-blames-nra-for-santa-fe-school-shooting/',
 'https://www.infowars.com/video-triggered-liberal-student-freaks-out-over-anti-socialist-booth/',
 'https://www.infowars.com/video-hollywood-actress-attends-anti-gun-protest-with-armed-guards/',
 'https://www.infowars.com/hawaii-volcano-prompts-new-warning-heed-evacuation-order-or-face-arrest/',
 'https://www.infowars.com/trump-moves-to-ban-most-transgender-people-from-serving-in-military/',
 'https://www.infowars.com/nolte-media-seek-to-destroy-laura-ingraham-because-shes-a-conservative-woman/',
 'https://www.infowars.com/new-study-finds-climate-change-alarmists-are-less-eco-friendly-than-skeptics/',
 'https://www.infowars.com/acosta-on-trump-meeting-with-kim-kardashian-she-shouldnt-be-here-talking-about-prison-reform/',
 'https://www.infowars.com/poll-double-the-amount-of-americans-think-young-black-people-doing-better-under-trump-than-obama/',
 'https://www.infowars.com/homeless-man-breaks-into-cali-govs-house-hes-an-open-door-policy-kind-of-guy-so-i-figured-the-door-would-be-unlocked/',
 'https://www.infowars.com/im-not-a-criminal-but-im-going-to-prison-for-owning-a-legal-handgun-in-new-york/',
 'https://www.infowars.com/federal-officials-lose-track-of-nearly-1500-migrant-children-in-us/',
 'https://www.infowars.com/suspect-arrested-in-connection-with-suspicious-packages-sent-to-military-bases/',
 'https://www.infowars.com/st-louis-jewish-cemetery-vandalism-was-carried-out-by-man-on-drugs-not-hate-filled-trump-supporter/',
 'https://www.infowars.com/joy-reid-could-face-charges-for-lying-to-fbi/',
 'https://www.infowars.com/msnbcs-matthews-people-should-expect-basic-restrictions-on-gun-rights/',
 'https://www.infowars.com/pjw-i-support-the-parkland-students/',
 'https://www.infowars.com/march-for-un-gun-grabbers-descends-on-washington/',
 'https://www.infowars.com/google-searches-for-buy-ar-15-surge-after-march-for-our-lives-rally/',
 'https://www.infowars.com/trump-top-north-korean-official-headed-to-u-s-to-discuss-summit/',
 'https://www.infowars.com/about-alex-jones/',
 'https://www.infowars.com/trump-and-mexican-president-spar-over-border-wall-again/',
 'https://www.infowars.com/david-hogg-reddit-post-celebrates-mosquitoes-killing-billions-of-humans/',
 'https://www.infowars.com/self-centered-self-serving-jackass-fbi-insiders-furious-after-comey-interview/',
 'https://www.infowars.com/professor-vows-to-boost-female-students-grades-to-offset-gender-imbalances/',
 'https://www.infowars.com/sketchy-porn-lawyer-threatens-people-not-to-look-into-financial-background/',
 'https://www.infowars.com/huge-republicans-now-6-points-ahead-in-congressional-poll/',
 'https://www.infowars.com/watch-alex-jones-show/',
 'https://www.infowars.com/ted-cruz-endorses-donald-trump-in-2020/',
 'https://www.infowars.com/donald-trump-called-the-iraq-war-a-disaster-his-new-national-security-adviser-was-its-biggest-cheerleader/',
 'https://www.infowars.com/facebook-is-now-ranking-news-organizations-based-on-trustworthiness/',
 'https://www.infowars.com/david-hoggs-sister-complains-her-school-now-feels-like-a-prison/',
 'https://www.infowars.com/fbi-informant-speaks-says-feds-asking-new-questions-about-clintons/',
 'https://www.infowars.com/broken-promise-trump-gop-congress-give-planned-parenthood-500-million-in-taxpayer-funds/',
 'https://www.infowars.com/cnns-anderson-cooper-trumps-fox-interview-like-listening-to-the-rantings-of-richard-nixon/',
 'https://www.infowars.com/ronan-farrow-clinton-tried-to-cancel-interview-over-weinstein-investigation/',
 'https://www.infowars.com/nfl-weighs-15-yard-penalties-for-kneeling-during-national-anthem-report/',
 'https://www.infowars.com/roger-stone-mueller-can-indict-a-ham-sandwich-but-im-not-interested-in-being-his-lunch/',
 'https://www.infowars.com/texas-teen-beaten-hot-cooking-oil-poured-on-her-after-refusing-arranged-marriage-police/',
 'https://www.infowars.com/white-professor-banned-from-diner-after-complaining-about-too-many-whites/#disqus_thread',
 'https://www.infowars.com/gop-voters-stick-with-pro-trump-candidates-in-senate-primaries/',
 'https://www.infowars.com/justice-department-watchdog-probes-comey-memos-over-classified-information/',
 'https://www.infowars.com/clapper-busted-leaking-dossier-details-to-cnns-jake-tapper-lying-to-congress-about-it/',
 'https://www.infowars.com/live-trump-speaks-in-ohio-on-tax-reform/',
 'https://www.infowars.com/judge-napolitano-political-class-must-have-known-about-schneiderman-sex-abuse/',
 'https://www.infowars.com/illinois-house-approves-plan-to-replace-armed-officers-in-schools-with-mental-health-professionals/',
 'https://www.infowars.com/roger-stones-claim-of-a-2016-julian-assange-meeting-draws-scrutiny/',
 'https://www.infowars.com/deerfield-illinois-passes-assault-weapons-ban-effective-june-13/',
 'https://www.infowars.com/msm-inflates-marchforourlives-number-by-half-a-million/',
 'https://www.infowars.com/fake-news-cnn-launches-investigation-into-disappearance-of-melania-trump/#disqus_thread',
 'https://www.infowars.com/broward-superintendent-defends-program-which-shielded-school-shooter-nikolas-cruz-from-arrest/',
 'https://www.infowars.com/u-s-appeals-against-ruling-that-trump-could-not-block-twitter-followers/',
 'https://www.infowars.com/mayor-who-honored-stormy-daniels-settled-500000-sexual-harassment-claim-in-2016/',
 'https://www.infowars.com/soros-drops-1-5-million-in-san-diego-for-far-left-district-attorney-candidate/',
 'https://www.infowars.com/president-trump-calls-for-documents-regarding-campaign-infiltration/',
 'https://www.infowars.com/brennan-trumps-fawning-attitude-toward-russia-means-they-have-something-on-him/',
 'https://www.infowars.com/cohen-would-turn-against-president-if-charged-counselor-warned-trump/',
 'https://www.infowars.com/calif-results-republican-advances-in-race-for-governor-dems-avoid-lock-out-in-key-races/',
 'https://www.infowars.com/cnn-commentator-national-anthem-is-problematic/',
 'https://www.infowars.com/parkland-survivor-arming-teachers-is-a-plot-for-the-nra/',
 'https://www.infowars.com/nbcs-chuck-todd-still-hopeful-for-gun-control-after-texas-shooting/',
 'https://www.infowars.com/texas-governor-announces-plan-to-protect-schools-from-mass-shooters/',
 'https://www.infowars.com/marchforourlives-speaker-admits-true-gun-control-plans/',
 'https://www.infowars.com/gun-rights-groups-file-several-lawsuits-against-illinois-town-over-new-gun-ban/',
 'https://www.infowars.com/donald-trump-our-country-is-being-stolen-by-illegals/',
 'https://www.infowars.com/breaking-top-uk-betting-sites-say-trump-set-to-win-nobel-peace-prize/',
 'https://www.infowars.com/poll-democratic-party-could-be-too-liberal-for-voters/',
 'https://www.infowars.com/jailed-senate-candidate-details-plan-to-take-down-elizabeth-warren/',
 'https://www.infowars.com/trump-distances-wh-from-saboteur-boltons-libya-model-plan-for-nk-scales-back-military-drill/',
 'https://www.infowars.com/fresno-state-has-deep-concerns-over-prof-who-celebrated-barbara-bushs-death/',
 'https://www.infowars.com/establishment-loses-big-as-grassroots-candidates-surge-in-texas-georgia/',
 'https://www.infowars.com/trump-congratulates-mueller-on-second-year-of-greatest-witch-hunt-in-american-history/',
 'https://www.infowars.com/roger-stone-releases-credit-card-flight-and-hotel-records-nowhere-near-london/',
 'https://www.infowars.com/hillary-clinton-i-gave-some-thought-to-leaving-country-after-trump-won/',
 'https://www.infowars.com/people-actually-found-a-way-to-use-melanias-surgery-to-attack-trump/',
 'https://www.infowars.com/facebook-sent-a-doctor-on-a-secret-mission-to-ask-hospitals-to-share-patient-data/',
 'https://www.infowars.com/voters-may-get-chance-to-vote-on-splitting-california-into-3-states/',
 'https://www.infowars.com/militant-vegan-tries-to-publicly-shame-woman-for-buying-crying-kid-an-ice-cream/',
 'https://www.infowars.com/after-a-cia-career-in-shadows-gina-haspel-to-face-the-spotlight-of-controversy/',
 'https://www.infowars.com/voters-more-likely-now-to-see-mueller-probe-as-partisan-witch-hunt/',
 'https://www.infowars.com/sharyl-attkisson-creates-detailed-timeline-showing-collusion-against-trump/',
 'https://www.infowars.com/nancy-pelosi-defends-ms-13-from-donald-trumps-mean-words/',
 'https://www.infowars.com/poll-dem-edge-in-generic-congressional-ballot-sinks-to-just-4-points/',
 'https://www.infowars.com/poll-trump-approval-hits-highest-mark-since-first-100-days-in-office/',
 'https://www.infowars.com/irs-systems-crash-on-tax-day/',
 'https://www.infowars.com/tennessee-state-senate-votes-to-build-victims-of-abortion-monument/',
 'https://www.infowars.com/video-clinton-lauds-efforts-to-censor-alternative-media/',
 'https://www.infowars.com/robert-mueller-allegedly-pinpoints-four-main-questions-he-hopes-to-ask-trump/',
 'https://www.infowars.com/breaking-trump-towers-50th-floor-on-fire/',
 'https://www.infowars.com/watch-five-cartel-attacks-in-24-hours-against-mexican-border-state-police/',
 'https://www.infowars.com/rod-rosensteins-wife-a-mystery-woman-of-conflict/',
 'https://www.infowars.com/cnn-uses-sexual-assault-allegations-against-schneiderman-to-bash-trump/',
 'https://www.infowars.com/anti-trump-leftist-tries-to-shoot-up-trump-golf-resort-in-florida/',
 'https://www.infowars.com/islamic-group-asking-u-s-residents-if-theyre-american-citizens-is-a-white-supremacist-agenda/',
 'https://www.infowars.com/parkland-gun-control-activists-driving-americans-toward-2nd-amendment/',
 'https://www.infowars.com/giuliani-trump-reimbursed-cohen-for-money-paid-to-stormy-daniels-it-wasnt-campaign-money/',
 'https://www.infowars.com/extreme-vetting-state-dept-to-demand-tourists-social-media-history/',
 'https://www.infowars.com/south-carolina-introduces-secession-bill-over-gun-rights/',
 'https://www.infowars.com/bunkers-for-bureaucrats-dc-elite-prepping-for-bug-out/',
 'https://www.infowars.com/trump-hints-he-will-fire-robert-mueller/',
 'https://www.infowars.com/dershowitz-judge-in-manafort-case-blew-whistle-on-mueller-probe/',
 'https://www.infowars.com/austin-bomber-said-attacks-not-political-left-screams-white-terrorism-anyway/',
 'https://www.infowars.com/oregon-initiative-requires-gun-owners-to-surrender-assault-weapons/',
 'https://www.infowars.com/ex-fbi-agent-comey-putting-himself-into-perjury-trap-with-upcoming-book/',
 'https://www.infowars.com/rank-and-file-fbi-agents-sickened-by-comey-and-mccabe-want-to-come-forward-and-testify/',
 'https://www.infowars.com/trump-to-give-full-pardon-to-dinesh-dsouza/',
 'https://www.infowars.com/video-hollywood-liberals-give-stormy-daniels-key-to-city-defend-ms-13/',
 'https://www.infowars.com/veterans-discuss-sessions-and-dirty-doj-over-memorial-day-weekend/',
 'https://www.infowars.com/scientists-nuke-attack-on-washington-dc-would-kill-280000-within-48-hours/',
 'https://www.infowars.com/lawsuit-describes-pervasively-hostile-anti-jewish-atmosphere-at-san-francisco-state/',
 'https://www.infowars.com/university-warns-non-mexican-students-against-partying-on-cinco-de-mayo/',
 'https://www.infowars.com/and-the-worst-city-in-america-for-2018-is/',
 'https://www.infowars.com/california-sheriff-why-wont-the-state-allow-us-to-enforce-immigration-law/',
 'https://www.infowars.com/firesessions-now-or-hes-in-until-2021/',
 'https://www.infowars.com/melania-trump-hasnt-been-on-a-single-magazine-cover-since-trump-took-office/',
 'https://www.infowars.com/soros-consultants-pac-could-influence-da-races-in-oregon/',
 'https://www.infowars.com/jailed-senate-candidate-warns-about-donating-to-boston-childrens-hospital/',
 'https://www.infowars.com/oconus-lures-strzok-page-texts-suggest-multiple-spies-targeted-trump-officials/',
 'https://www.infowars.com/gunman-in-oklahoma-restaurant-killed-by-armed-civilian/',
 'https://www.infowars.com/confirmed-school-shooter-nikolas-cruz-was-shielded-from-arrest-to-fight-systemic-racism/',
 'https://www.infowars.com/cnns-cuomo-slammed-for-saying-no-one-is-calling-for-repeal-of-second-amendment/',
 'https://www.infowars.com/msnbc-speculates-about-trumps-sexual-dysfunction/',
 'https://www.infowars.com/top-de-blasio-aide-arrested-for-illegal-weapons-possession/',
 'https://www.infowars.com/former-trump-aide-fbi-informant-was-not-the-only-obama-plant-in-campaign/',
 'https://www.infowars.com/young-turks-co-host-conveniently-timed-terrorist-attack-could-help-trump-in-mid-terms/',
 'https://www.infowars.com/trudeau-sees-high-chance-of-nafta-deal-with-us-mexico/',
 'https://www.infowars.com/exposed-immigrant-caravan-not-refugees/',
 'https://www.infowars.com/we-sell-ar-15s-because-were-not-dicks-pawn-shop-trolls-sporting-goods-chain/',
 'https://www.infowars.com/dhs-confirms-rogue-cellular-eavesdropping-device-may-have-been-used-near-white-house/',
 'https://www.infowars.com/dc-considers-allowing-16-year-olds-to-vote/',
 'https://www.infowars.com/hollywood-sex-cult-linked-to-rothschilds-clintons/',
 'https://www.infowars.com/caravan-releases-list-of-demands-trump-expected-to-comply/',
 'https://www.infowars.com/homeland-security-to-compile-database-of-journalists-and-media-influencers/',
 'https://www.infowars.com/students-from-300-schools-pledge-to-walk-out-of-class-in-stand-for-the-second-event/',
 'https://www.infowars.com/trump-on-eric-schneiderman-in-2013-tweet-wait-and-see-worse-than-spitzer-or-weiner/',
 'https://www.infowars.com/twitter-ceo-shares-and-raves-about-article-calling-for-dem-victory-in-second-civil-war/',
 'https://www.infowars.com/the-war-on-our-border-ignored-by-defense-dept/',
 'https://www.infowars.com/trump-mexico-must-stop-immigrant-caravans/',
 'https://www.infowars.com/media-misled-on-nra-annual-meeting-gun-policy/',
 'https://www.infowars.com/early-trump-ally-secures-senate-nomination/',
 'https://www.infowars.com/jimmy-kimmel-apologizes-for-vulgar-comments-but-skips-apology-to-melania-trump/',
 'https://www.infowars.com/bilderberg-globalists-concerned-about-populist-uprising-in-europe/',
 'https://www.infowars.com/confusion-msnbc-brian-williams-calls-president-trump-obama-after-syria-bombing/',
 'https://www.infowars.com/watch-president-trump-participates-in-roundtable-on-immigration-and-ms-13/',
 'https://www.infowars.com/watch-live-will-trump-pardon-himself/',
 'https://www.infowars.com/sjws-killed-climate-change-politics/',
 'https://www.infowars.com/charges-dropped-against-most-turkish-officers-accused-in-d-c-clash/',
 'https://www.infowars.com/maxine-waters-republicans-will-have-to-prove-their-patriotism-by-impeaching-trump/',
 'https://www.infowars.com/attack-at-air-force-base-in-california-reportedly-being-treated-as-terrorism/',
 'https://www.infowars.com/the-shady-business-dealings-of-sheriff-lombardo-his-secret-wife/',
 'https://www.infowars.com/brzezinski-trump-is-a-stone-cold-racist/',
 'https://www.infowars.com/report-immigration-officials-seek-to-prosecute-parents-illegally-entering-us/',
 'https://www.infowars.com/upcoming-roseanne-episode-to-feature-muslim-neighbors/',
 'https://www.infowars.com/nightly-news/',
 'https://www.infowars.com/starbucks-to-close-8000-us-stores-for-racial-sensitivity-training/',
 'https://www.infowars.com/rand-paul-warns-new-us-war-powers-act-will-rubber-stamp-global-conflict/',
 'https://www.infowars.com/hillary-clinton-calls-for-new-national-commission-to-investigate-russian-cyber-interference/',
 'https://www.infowars.com/read-the-strozk-page-texts-the-doj-handed-over-to-congress/',
 'https://www.infowars.com/reuters-weekly-poll-reflects-upswing-in-support-for-president-trump/',
 'https://www.infowars.com/ann-coulter-to-trump-you-built-golf-course-in-scotland-skating-rink-in-central-park-now-build-border-wall/#disqus_thread',
 'https://www.infowars.com/obama-our-democracy-may-not-survive/',
 'https://www.infowars.com/biden-the-2nd-amendment-is-being-very-badly-interpreted/',
 'https://www.infowars.com/trump-slams-white-house-correspondents-dinner-as-a-very-big-boring-bust/',
 'https://www.infowars.com/cnn-mocks-trump-base-very-very-much-not-involved-in-what-is-going-on-in-us/',
 'https://www.infowars.com/wp-content/uploads/2018/05/230106_image.jpg',
 'https://www.infowars.com/residents-of-illinois-village-have-60-days-to-surrender-guns-or-face-1000-a-day-fine/',
 'https://www.infowars.com/wsj-the-fbi-hid-a-mole-in-the-trump-campaign/',
 'https://www.infowars.com/david-hoggs-call-for-boycott-of-investment-giants-blackrock-and-vanguard-falls-flat/',
 'https://www.infowars.com/exclusive-relative-of-santa-fe-shooting-victim-blame-bad-parenting-not-guns/',
 'https://www.infowars.com/report-immigrants-with-detainers-released-by-sanctuary-new-york-commit-more-crimes/',
 'https://www.infowars.com/explosion-during-hostage-situation-injures-six-officers/',
 'https://www.infowars.com/joy-reid-apologizes-i-genuinely-do-not-believe-i-wrote-those-hateful-things/',
 'https://www.infowars.com/trump-to-impose-total-ban-on-luxury-german-cars-report/',
 'https://www.infowars.com/callers-struggle-to-list-off-obamas-accomplishments/',
 'https://www.infowars.com/ann-coulter-to-trump-you-built-golf-course-in-scotland-skating-rink-in-central-park-now-build-border-wall/',
 'https://www.infowars.com/southwest-flight-forced-to-land-after-bird-strike-day-after-plane-engine-catastrophe-kills-passenger/',
 'https://www.infowars.com/fake-news-cnn-launches-investigation-into-disappearance-of-melania-trump/',
 'https://www.infowars.com/meghan-mccain-scolds-comey-stop-pretending-you-arent-political/',
 'https://www.infowars.com/big-blue-bellyflop-dem-advantage-in-generic-ballot-hits-new-low/',
 'https://www.infowars.com/liberals-want-to-ban-guns-that-dont-exist/',
 'https://www.infowars.com/trump-those-who-wont-stand-for-national-anthem-shouldnt-be-in-the-country/',
 'https://www.infowars.com/fmr-deputy-director-mccabe-admonished-fbi-officials-for-his-own-leaks/',
 'https://www.infowars.com/trump-is-getting-angrier/',
 'https://www.infowars.com/invisible-campaign-dem-presidential-hopefuls-flock-to-trump-country/',
 'https://www.infowars.com/kanyes-real-crime-encouraging-black-people-to-think-for-themselves/',
 'https://www.infowars.com/heads-will-roll-under-second-special-counsel-investigation/',
 'https://www.infowars.com/nyt-reporter-i-wanted-to-scream-at-every-critic-of-hillary-clinton/',
 'https://www.infowars.com/bloomberg-says-voters-miss-barack-obama-and-his-largely-corruption-free-administration/',
 'https://www.infowars.com/video-msnbc-host-scarborough-says-white-house-physician-is-like-hitlers-doctor/',
 'https://www.infowars.com/diamond-and-silk-call-on-trump-to-probe-social-media-giants/',
 'https://www.infowars.com/chelsea-manning-tweets-suicide-note-pictured-standing-over-building-ledge/',
 'https://www.infowars.com/paul-ryan-should-move-to-impeach-federal-judge-kimba-wood/',
 'https://www.infowars.com/trump-excludes-dems-media-from-state-dinner/',
 'https://www.infowars.com/hawaii-lawmakers-approve-medical-aid-in-dying-for-terminally-ill/',
 'https://www.infowars.com/nunes-dnc-lawsuit-is-a-scam/',
 'https://www.infowars.com/u-s-judge-rules-iran-must-pay-6-billion-to-9-11-victims/',
 'https://www.infowars.com/project-veritas-nj-teachers-union-president-covers-up-child-abuse-in-schools/',
 'https://www.infowars.com/video-students-shocked-that-obama-also-sent-troops-to-border/',
 'https://www.infowars.com/video-cnns-tapper-says-mccain-is-american-hero-for-not-wanting-trump-at-funeral/',
 'https://www.infowars.com/report-las-vegas-sheriffs-office-covering-up-domestic-abuse-scandal/',
 'https://www.infowars.com/lowest-rated-show-on-fox-news-outperforms-highest-rated-show-on-cnn/',
 'https://www.infowars.com/cnn-reporter-complains-trump-empowers-dictators-against-the-media/',
 'https://www.infowars.com/trump-jr-slams-zuckerberg-over-instagram-bias/',
 'https://www.infowars.com/rachel-maddow-mika-brzezinski-other-female-journalists-circle-wagons-for-tom-brokaw/',
 'https://www.infowars.com/gorka-to-grassroots-trump-is-the-kryptonite-of-political-correctness/#disqus_thread',
 'https://www.infowars.com/trump-admin-charges-iranians-for-hacking-campaign-against-u-s/',
 'https://www.infowars.com/cartels-make-500-million-annually-smuggling-illegals-into-america/',
 'https://www.infowars.com/leftists-puzzled-why-koch-brothers-are-funding-political-ads-praising-dems-on-immigration/',
 'https://www.infowars.com/martin-luther-king-tried-to-defend-himself-with-a-gun-but-govt-took-away-his-right-to-do-so/',
 'https://www.infowars.com/watch-tucker-and-alan-dershowitz-ruin-james-comeys-night/',
 'https://www.infowars.com/kanye-west-blasts-thought-police-after-hes-attacked-for-endorsing-conservative-commentator/',
 'https://www.infowars.com/dem-muslim-candidate-for-michigan-governor-tells-gop-opponent-muslims-hate-you/',
 'https://www.infowars.com/illegal-alien-accused-of-ramming-motorcyclist-off-the-road-arrested/',
 'https://www.infowars.com/busted-joy-reid-misspelling-suggests-she-did-write-homophobic-blog-posts/',
 'https://www.infowars.com/laura-ingrahams-ratings-shoot-up-despite-leftist-boycott/',
 'https://www.infowars.com/poll-half-of-republicans-think-media-should-be-described-as-enemy-of-people/',
 'https://www.infowars.com/nbc-staffers-felt-forced-to-sign-letter-defending-brokaw/',
 'https://www.infowars.com/liberal-solutions-school-district-arms-teachers-with-16-inch-baseball-bats/',
 'https://www.infowars.com/white-professor-banned-from-diner-after-complaining-about-too-many-whites/',
 'https://www.infowars.com/republican-democrat-establishment-unite-to-shaft-america-with-1-3-trillion-omnibus-bill/',
 'https://www.infowars.com/about-alex-jones-show/',
 'https://www.infowars.com/hillary-clinton-santa-fe-school-shooting-should-inspire-soul-searching-gun-control/',
 'https://www.infowars.com/poll-confirms-77-think-traditional-media-is-fake-news/',
 'https://www.infowars.com/benghazi-survivor-tears-up-the-view-for-calling-gop-probe-petty/',
 'https://www.infowars.com/spygate-trump-says-comey-was-terrible-and-corrupt-inflicted-great-pain/',
 'https://www.infowars.com/texas-to-send-up-to-1400-troops-to-u-s-mexico-border/',
 'https://www.infowars.com/drudge-hits-trump-over-call-to-take-away-reporters-credentials/',
 'https://www.infowars.com/fund-the-wall-from-defense-budget/',
 'https://www.infowars.com/sacramento-protester-blocking-traffic-walks-in-front-of-sheriffs-suv-gets-hit-claims-victimhood/',
 'https://www.infowars.com/new-book-determines-kellyanne-conway-is-the-number-one-leaker-in-the-white-house/',
 'https://www.infowars.com/maxine-waters-too-dangerous-to-wait-for-2020-to-get-trump-out-of-office/',
 'https://www.infowars.com/drink-a-toast-and-share-this-ghost-to-firesessions/',
 'https://www.infowars.com/cnns-van-jones-admits-liberals-waste-so-much-time-freaking-out-about-trump/',
 'https://www.infowars.com/swarms-of-quakes-rattle-hawaiis-big-island-as-possible-eruption-looms/',
 'https://www.infowars.com/southern-poverty-law-center-amasses-nearly-half-a-billion-in-assets-in-trump-era/',
 'https://www.infowars.com/broward-county-sheriffs-deputy-who-questioned-parkland-shootings-gun-control-agenda-dies-unexpectedly/',
 'https://www.infowars.com/orange-county-city-votes-again-to-opt-out-of-californias-sanctuary-state-law/',
 'https://www.infowars.com/hey-sessions-arrestobamaalready/',
 'https://www.infowars.com/report-fake-news-nearly-caused-trump-to-fire-mueller/',
 'https://www.infowars.com/trump-claims-he-could-beat-up-joe-biden-hed-go-down-hard-and-fast-crying-all-the-way/',
 'https://www.infowars.com/cancer-patient-cured-by-experimental-treatment/',
 'https://www.infowars.com/listen-to-the-radio-show-archive/',
 'https://www.infowars.com/nyt-columnist-worries-mueller-investigation-actually-helping-trump/',
 'https://www.infowars.com/omnibus-spending-bill-allows-more-illegal-aliens-to-be-released-into-u-s-through-catch-and-release/',
 'https://www.infowars.com/trump-decries-fake-reporting-on-melania-says-shes-doing-well/',
 'https://www.infowars.com/wp-content/uploads/2018/05/wrong-way-dt-600.jpg',
 'https://www.infowars.com/west-hollywood-to-present-stormy-daniels-with-key-to-the-city/',
 'https://www.infowars.com/on-4-20-chuck-schumer-pushes-to-decriminalize-marijuana-at-federal-level/',
 'https://www.infowars.com/giuliani-threatens-legal-battle-with-mueller-over-subpoena/',
 'https://www.infowars.com/its-time-for-an-aggressive-assault-on-the-entities-destroying-our-nation/',
 'https://www.infowars.com/bolton-white-house-leakers-should-be-ashamed/',
 'https://www.infowars.com/video-protesters-say-ban-assault-weapons-whatever-those-are/',
 'https://www.infowars.com/robert-mueller-allegedly-pinpoints-four-main-questions-he-hopes-to-ask-trump/#disqus_thread',
 'https://www.infowars.com/legacy-media-wants-infowars-shut-down-over-march-for-our-lives-hitler-youth-comparison/',
 'https://www.infowars.com/gun-sales-soar-set-record-in-march-amid-push-for-new-gun-control-measures/',
 'https://www.infowars.com/trump-threatens-to-close-down-the-country-over-funding-for-border-wall/',
 'https://www.infowars.com/its-time-for-an-aggressive-assault-on-the-entities-destroying-our-nation/#disqus_thread',
 'https://www.infowars.com/hundreds-of-police-chiefs-tell-congress-not-to-pass-concealed-carry-bill/',
 'https://www.infowars.com/wapo-columnist-trump-supporters-are-immoral-and-un-american/',
 'https://www.infowars.com/rubio-warns-that-fake-videos-pose-a-major-threat-to-our-democracy/',
 'https://www.infowars.com/trumps-fake-news-fight-has-helped-media-ratings-and-readership/',
 'https://www.infowars.com/media-inquiries/',
 'https://www.infowars.com/report-dozens-of-criminal-illegal-immigrants-shielded-by-nycs-sanctuary-policy-rearrested-for-new-crimes/',
 'https://www.infowars.com/absolutely-deranged-matthews-leads-fact-free-gun-control-panel-filled-with-churlish-rhetoric/',
 'https://www.infowars.com/gop-wins-ariz-special-election-close-margin-a-warning-for-midterms/',
 'https://www.infowars.com/trump-slams-mueller-hoax-as-setup-trap/',
 'https://www.infowars.com/dems-attack-trump-for-signing-right-to-try-drug-bill-into-law/',
 'https://www.infowars.com/wikileaks-to-countersue-democrats-discovery-is-going-to-be-amazing-fun/',
 'https://www.infowars.com/chelsea-clinton-trump-degrades-what-it-means-to-be-american/',
 'https://www.infowars.com/cnn-snorts-what-kind-of-dumbass-colleges-dont-want-david-hogg/',
 'https://www.infowars.com/federal-judge-releases-illegal-alien-who-rammed-car-into-daycare-center/#disqus_thread',
 'https://www.infowars.com/watch-soldier-leads-cops-on-chase-after-stealing-armored-vehicle/',
 'https://www.infowars.com/report-sex-workers-to-expose-politicians-for-passing-anti-trafficking-bill/',
 'https://www.infowars.com/whats-obamas-fec-commissioner-doing-for-the-massachusetts-gop/',
 'https://www.infowars.com/bilderberg-globalists-concerned-about-populist-uprising-in-europe/#disqus_thread',
 'https://www.infowars.com/nancy-pelosi-on-supreme-court-ruling-bake-that-cake-christians/',
 'https://www.infowars.com/hate-hoax-teens-story-about-being-kidnapped-by-white-supremacists-was-a-lie/',
 'https://www.infowars.com/report-dhs-secretary-nielsen-implored-not-to-quit-by-john-kelly-as-illegal-immigration-skyrockets/',
 'https://www.infowars.com/howard-u-students-occupy-campus-building-demand-gender-sex-police-changes-due-to-systemic-oppression/',
 'https://www.infowars.com/nbc-news-star-hallie-jackson-calls-release-of-us-prisoners-choreographed-and-staged/',
 'https://www.infowars.com/watch-moderator-invokes-nazism-when-talking-about-america-hillary-has-bizarre-response/',
 'https://www.infowars.com/cnn-admits-dems-lead-in-2018-midterm-election-polls-evaporating/',
 'https://www.infowars.com/illegal-scales-current-border-fence-in-under-2-minutes/',
 'https://www.infowars.com/study-sanctuary-cities-nearly-double-under-trumps-stricter-enforcement/',
 'https://www.infowars.com/whoopi-goldberg-riots-over-mueller-firing-would-be-fun-to-watch/',
 'https://www.infowars.com/brennan-strzok-and-kerry-allegedly-set-spy-traps-for-trump-team-hunt-for-fbi-mole-intensifies/',
 'https://www.infowars.com/here-are-a-few-of-the-most-obnoxious-signs-at-the-march-for-our-lives-rally/',
 'https://www.infowars.com/i-feel-like-the-minority-americans-tell-washington-post-theyre-sick-of-mass-immigration/',
 'https://www.infowars.com/ted-nugent-calls-parkland-student-activists-liars-they-have-no-soul/',
 'https://www.infowars.com/roger-stone-says-trump-may-not-run-in-2020-pledges-to-line-up-challenger-to-pence-haley-ticket/',
 'https://www.infowars.com/waco-25-yrs-ago-us-used-chemical-weapons-against-its-children/',
 'https://www.infowars.com/lawless-atlanta-police-to-stop-responding-to-shoplifting-calls/',
 'https://www.infowars.com/hundreds-of-sheriffs-demand-congress-build-the-wall-crack-down-on-illegal-immigration/',
 'https://www.infowars.com/trump-fake-news-cnn-is-dead/',
 'https://www.infowars.com/trump-wins-mexico-to-disband-illegal-immigrant-caravans/',
 'https://www.infowars.com/nras-dana-loesch-the-media-needs-to-stop-creating-monsters-who-commit-mass-shootings/',
 'https://www.infowars.com/legal-marijuana-states-have-lower-opioid-use-new-studies-show/',
 'https://www.infowars.com/central-american-caravan-women-and-children-enter-u-s-defying-trump/',
 'https://www.infowars.com/progressive-radio-host-trump-shouldnt-call-ms-13-animals/',
 'https://www.infowars.com/h-r-mcmasters-fathers-death-labeled-suspicious-multiple-agencies-investigating/',
 'https://www.infowars.com/woke-maxine-waters-plays-to-empty-seats-as-only-10-millennials-show-up-to-campaign-event/',
 'https://www.infowars.com/comey-admits-he-may-not-have-reopened-hillary-probe-if-he-thought-she-could-lose/',
 'https://www.infowars.com/trump-slams-disgraceful-mueller-over-leaked-questions/',
 'https://www.infowars.com/comeys-memos-on-trump-meetings-leaked-online-full-text/',
 'https://www.infowars.com/texas-gov-greg-abbott-signals-support-for-two-gun-control-measures/',
 'https://www.infowars.com/liberal-media-censors-pro-second-amendment-teen/',
 'https://www.infowars.com/democratic-donors-paid-50-million-for-new-anti-trump-research/',
 'https://www.infowars.com/candace-owens-explains-the-black-card/',
 'https://www.infowars.com/comey-admits-he-hid-that-dems-funded-steele-dossier-from-trump-wasnt-necessary-for-my-goal/',
 'https://www.infowars.com/ice-raid-on-sanctuary-chicago-nets-156-illegals-sex-traffickers-rapists-drunk-drivers-drug-dealers-thieves/',
 'https://www.infowars.com/flashback-hollywood-star-takes-epic-public-stand-for-easter/',
 'https://www.infowars.com/cnns-acosta-trump-supporters-dont-have-all-their-faculties/',
 'https://www.infowars.com/schumer-its-time-to-vote-on-legislation-protecting-mueller/',
 'https://www.infowars.com/texas-rep-bombing-suspects-roommate-a-person-of-interest/',
 'https://www.infowars.com/washpo-explaining-to-a-leftist-how-guns-work-is-gunsplaining/',
 'https://www.infowars.com/chris-hedges-u-s-citizens-are-living-in-an-inverted-totalitarian-country/',
 'https://www.infowars.com/son-of-boston-police-captain-pleads-guilty-to-terrorism-charges/',
 'https://www.infowars.com/him-too-anti-trump-nyc-ag-eric-schneiderman-resigns-after-sex-abuse-allegations/',
 'https://www.infowars.com/ice-will-detain-pregnant-women-ending-previous-policy/',
 'https://www.infowars.com/bill-maher-defends-ingraham-parkland-student-calling-for-a-boycott-is-wrong/',
 'https://www.infowars.com/obama-era-political-prisoner-writes-scathing-letter-to-ag-jeff-sessions/',
 'https://www.infowars.com/msm-fail-santa-fe-students-refuse-to-give-msnbc-gun-control-soundbite/',
 'https://www.infowars.com/indiana-school-shooter-detained-2-critical/',
 'https://www.infowars.com/trump-threatens-to-veto-omnibus-spending-bill-over-daca-and-the-border-wall/',
 'https://www.infowars.com/trump-trolls-pelosi-she-came-out-in-favor-of-ms-13/',
 'https://www.infowars.com/franciscan-university-claims-facebook-rejected-ad-because-it-shows-jesus-on-the-cross/',
 'https://www.infowars.com/donald-trump-announces-plan-to-countersue-democrats-for-dnc-server/',
 'https://www.infowars.com/epstein-at-masters-of-the-universe-town-hall-google-favored-search-results-for-clinton-over-trump/',
 'https://www.infowars.com/canada-goes-cannabis/',
 'https://www.infowars.com/comedic-legend-mel-brooks-denounces-political-correctness/']
#Just make sure
info_links_2 = list(set(info_links_2))
#functions
def get_infowars_article(url):
    #tries requests
    page = requests.get(url)
    html = page.text
    return html

def parse_infowars_article(html):
    #BeautifulSoup the page
    soup = BeautifulSoup(html, 'lxml')
    title = soup.find('h1').text
    body = soup.find('div', class_='text').text

    article = {
        'title': title,
        'body': body,
        'source': 'Info wars',
        'num_source': 4
    }

    return article

def get_parsed_article_from_link(url):
    #runs functions on links
    return parse_infowars_article(get_infowars_article(url))
#phase 1 of pipeline
infowars_list_o_articles = []
infowars_problem_articles = []
for text in info_links_2:
    try:
        art = get_parsed_article_from_link(text.encode())
        infowars_list_o_articles.append(art)

    except:
        problem = text
        infowars_problem_articles.append(problem)
    time.sleep(3)
driver = webdriver.PhantomJS(service_args=['--ssl-protocol=any'])
#phase 2
for x in infowars_problem_articles:
    try:
        driver.get(x)
        time.sleep(3)
        soupy = BeautifulSoup(driver.page_source, 'lxml')
        title = soup.find('h1').text
        body = soup.find('div', class_='text').text

        articley = {
            'title': title,
            'body': body,
            'source': 'Info wars',
            'num_source': 4
        }
        infowars_list_o_articles.append(articley)
    except:
        pass
#starts client in Mongodb
client = MongoClient()
biased_news = client.project5.biased_news
#creates event and loads articles into Mongodb
db = client.events
biased_news = db.biased_news
biased_news.insert_many(infowars_list_o_articles)
