import requests
from bs4 import BeautifulSoup
import re
#The basics
import numpy as np
import pandas as pd

#Get them web sites
import requests

#Make sure slenium works
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import os

#Start the google driver
driver = webdriver.PhantomJS(service_args=['--ssl-protocol=any'])
#For inserting articles into Mongodb
from pymongo import MongoClient
#starts off on the politics page
url_rueters = 'https://www.reuters.com/politics'
response = requests.get(url_rueters)

def get_case_links_from_rueters(html):
    """
    scrolls through politics page 25 times to get article links
    """
    driver.get(html)
    time.sleep(3)

    SCROLL_PAUSE_TIME = 0.5
    # Get scroll height
    last_height = driver.execute_script("return document.body.scrollHeight")
    i = 0
    while i < 25:
    # Scroll down to bottom
        soup = BeautifulSoup(driver.page_source, 'lxml')
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    # Wait to load page
        time.sleep(SCROLL_PAUSE_TIME)
        i += 1
    return list(set(article['href'] for article in soup.find_all('a')))
#Start slenium on current url
'''driver = webdriver.PhantomJS(service_args=['--ssl-protocol=any'])
rueters_politics = get_case_links_from_rueters(url_rueters)'''
#Runs links through regex
'''links = []
regex = re.compile("https:\/\/www.reuters.com\/article\/[^']+")
linkstr = re.findall(regex, str(rueters_politics))
links.append(linkstr)'''
#cleans links into nice list
'''links_ = []
for linklist in links:
    for link in linklist:
        links_.append(link)'''
#Just feed the links in here
links_ = ['https://www.reuters.com/article/us-gymnastics-usa-congress/ex-michigan-state-university-head-to-testify-to-congress-on-abuse-of-athletes-idUSKCN1IU280',
 'https://www.reuters.com/article/us-iran-nuclear-merkel/merkel-must-talk-about-a-broader-iran-nuclear-deal-idUSKBN1IA1P0',
 'https://www.reuters.com/article/us-china-trade-southkorea-japan/china-says-hopes-to-work-with-japan-south-korea-on-fta-as-soon-as-possible-idUSKCN1IP0D4',
 'https://www.reuters.com/article/us-northkorea-usa-prisoners-family/family-of-detained-american-grateful-for-his-release-from-north-korea-idUSKBN1IA25Q',
 'https://www.reuters.com/article/us-iran-nuclear-bargain/iran-grand-bargain-all-but-impossible-as-u-s-exits-nuclear-pact-idUSKBN1I938L',
 'https://www.reuters.com/article/us-iran-nuclear-britain-suggestion/uk-says-follow-on-agreement-with-iran-could-meet-trump-concerns-idUSKBN1IA1X5',
 'https://www.reuters.com/article/us-usa-trade-nafta-congress/house-speaker-doubtful-of-nafta-passage-in-current-congress-idUSKCN1J21Y4',
 'https://www.reuters.com/article/us-usa-politics-iowa/democrat-running-for-iowa-governor-quits-after-sex-allegations-idUSKCN1IQ087',
 'https://www.reuters.com/article/us-usa-trump-tweet/trump-on-twitter-comey-national-anthem-nfl-idUSKCN1J11F9',
 'https://www.reuters.com/article/us-northkorea-usa-singapore-zone/trump-kim-summit-set-for-singapores-sentosa-island-white-house-idUSKCN1J1141',
 'https://www.reuters.com/article/us-usa-cfpb-boards/trumps-consumer-financial-chief-disbands-key-advisory-boards-idUSKCN1J22PN',
 'https://www.reuters.com/article/us-louisiana-secretary/louisiana-election-chief-resigns-amid-sexual-harassment-scandal-idUSKBN1I249R',
 'https://www.reuters.com/article/us-usa-trump-russia/trump-lawyer-giuliani-defends-legality-of-porn-star-payment-idUSKBN1I51S6',
 'https://www.reuters.com/article/us-usa-immigration-caravan-sessions/u-s-adding-prosecutors-judges-to-process-immigrants-at-mexico-border-idUSKBN1I32PW',
 'https://www.reuters.com/article/us-usa-diplomacy-health/u-s-sets-up-task-force-over-unexplained-diplomatic-health-incidents-idUSKCN1J12CF',
 'https://www.reuters.com/article/us-iran-nuclear-rouhani-reaction/rouhani-to-speak-on-iran-tv-after-trump-gives-nuclear-deal-decision-irna-idUSKBN1I92LW',
 'https://www.reuters.com/article/us-usa-trump-russia-lawyer/trump-replaces-white-house-lawyer-on-russia-probe-idUSKBN1I32EC',
 'https://www.reuters.com/article/us-iran-nuclear-instantview/instant-view-u-s-withdraws-from-iran-deal-idUSKBN1I92UA',
 'https://www.reuters.com/article/us-mideast-crisis-syria-israel-military/israel-says-mobilizing-some-reserve-troops-idUSKBN1I92WH',
 'https://www.reuters.com/article/us-israel-usa-diplomacy-whitehouse/trump-will-not-attend-u-s-embassy-opening-in-jerusalem-white-house-idUSKBN1I821D',
 'https://www.reuters.com/article/us-usa-trump-russia-cambridge-analytica/ex-trump-aide-bannon-promoted-culture-war-cambridge-analytica-whistleblower-idUSKCN1IH36S',
 'https://www.reuters.com/article/us-usa-court-trump/trump-complains-of-biased-courts-but-they-often-support-his-policies-idUSKBN1I919Z',
 'https://www.reuters.com/article/us-usa-trump-cohen/few-documents-seized-from-michael-cohen-deemed-privileged-in-first-review-idUSKCN1J0330',
 'https://www.reuters.com/article/us-northkorea-missiles-detainees-stateme/americans-released-by-north-korea-thank-trump-in-statement-idUSKBN1IA3JN',
 'https://www.reuters.com/article/us-milken-conference-highlights/highlights-goldmans-shrinking-equity-trading-desk-jp-morgans-erdoes-on-volatility-idUSKBN1I12FI',
 'https://www.reuters.com/article/us-iran-nuclear-poll/less-than-one-in-three-americans-support-u-s-pullout-from-iran-deal-idUSKBN1I92RA',
 'https://www.reuters.com/article/us-usa-election/black-candidate-makes-history-as-women-advance-in-u-s-midterms-idUSKCN1IN1D6',
 'https://www.reuters.com/article/us-northkorea-usa-detainees-freedom/former-detainees-say-freedom-came-fast-in-north-korea-idUSKBN1IA2DP',
 'https://www.reuters.com/article/us-iran-nuclear-britain-johnson-statemen/britain-says-world-should-hold-trump-to-his-word-on-finding-new-iran-solution-idUSKBN1IA1TF',
 'https://www.reuters.com/article/us-usa-trade-china/trump-floats-management-changes-instead-of-sanctions-for-chinas-zte-idUSKCN1IN27O',
 'https://www.reuters.com/article/us-usa-trump-haspel-manchin/democratic-senator-manchin-will-back-trump-cia-nominee-haspel-idUSKBN1IA34N',
 'https://www.reuters.com/article/us-usa-epa-autos/u-s-lawmakers-seek-details-from-epa-chief-on-fuel-economy-rule-changes-idUSKBN1I12CL',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-north-korea-immigration-fake-news-idUSKBN1I22KM',
 'https://www.reuters.com/article/us-usa-trump-rosenstein/trump-russia-probe-official-justice-department-will-not-be-extorted-amid-threats-idUSKBN1I24I2',
 'https://www.reuters.com/article/us-usa-congress-prison/u-s-house-passes-bipartisan-prison-reform-bill-idUSKCN1IN30V',
 'https://www.reuters.com/article/us-usa-trump-cohen/att-deal-with-cohen-specified-providing-advice-on-time-warner-merger-washington-post-idUSKBN1IC00A',
 'https://www.reuters.com/article/us-iran-nuclear-southkorea/south-korea-seeks-to-minimize-impact-on-its-firms-of-u-s-pullout-from-iran-deal-idUSKBN1IA20Y',
 'https://www.reuters.com/article/us-usa-trump-russia-subpoena/mueller-raises-possibility-of-trump-subpoena-former-trump-lawyer-idUSKBN1I301Y',
 'https://www.reuters.com/article/us-usa-sec-piwowar/sec-commissioner-piwowar-a-republican-to-step-down-idUSKBN1I828F',
 'https://www.reuters.com/article/us-usa-epa-pruitt-trump/trump-praises-epa-chief-pruitt-under-fire-for-ethics-spending-idUSKCN1J22XA',
 'https://www.reuters.com/article/us-iran-nuclear-germany-maas/u-s-offered-no-alternative-to-iran-nuclear-deal-germany-idUSKBN1IA19T',
 'https://www.reuters.com/article/us-usa-guns-nra-new-york/nra-sues-new-york-governor-regulator-for-blacklisting-campaign-idUSKBN1IC2AK',
 'https://www.reuters.com/article/us-usa-healthcare-medicare/u-s-medicare-reserves-seen-lasting-three-years-less-than-prior-forecast-idUSKCN1J12LX',
 'https://www.reuters.com/article/us-usa-congress-farmbill/u-s-house-defeats-farm-bill-sugar-amendment-amid-republican-immigration-spat-idUSKCN1II2W2',
 'https://www.reuters.com/article/us-usa-immigration-congress-daca/rebel-house-republicans-seek-to-force-dreamer-immigration-vote-idUSKBN1IA2UY',
 'https://www.reuters.com/article/us-china-trade-germany/china-says-has-good-potential-in-cooperation-with-germany-in-new-energy-cars-ai-idUSKCN1IP0CU',
 'https://www.reuters.com/article/us-northkorea-missiles-meeting/trump-says-date-place-set-for-north-korea-summit-idUSKBN1I51PK',
 'https://www.reuters.com/article/us-iran-nuclear-macron-rouhani/frances-macron-tells-irans-rouhani-to-stick-with-nuclear-deal-idUSKBN1IA2FK',
 'https://www.reuters.com/article/us-usa-trade-senate-mcconnell/u-s-senate-leader-paves-way-for-debating-trump-tariff-policy-idUSKCN1J12LF',
 'https://www.reuters.com/article/us-usa-trump-birthcontrol/trump-administration-sued-over-family-planning-program-shift-idUSKBN1I32BU',
 'https://www.reuters.com/article/us-iran-nuclear-netanyahu/netanyahu-hails-trump-over-iran-says-nuclear-deal-was-recipe-for-disaster-idUSKBN1I92PK',
 'https://www.reuters.com/article/us-northkorea-usa-singapore-airspace/singapore-to-restrict-airspace-during-u-s-north-korea-summit-idUSKCN1J20B3',
 'https://www.reuters.com/article/us-northkorea-missiles-prisoners/pompeo-expected-to-return-with-three-american-detainees-south-korean-official-idUSKBN1IA07E',
 'https://www.reuters.com/article/us-nuclear-iran-parliament/irans-parliament-speaker-says-u-s-breached-nuclear-deal-commitments-irna-idUSKBN1I91P6',
 'https://www.reuters.com/article/us-iran-nuclear-economy-deals-factbox/factbox-irans-deals-with-foreign-firms-since-easing-of-sanctions-in-2015-idUSKBN1IA1U7',
 'https://www.reuters.com/article/us-usa-trump-daniels-treasury/u-s-watchdog-probes-release-of-trump-lawyers-banking-details-report-idUSKBN1IA2VC',
 'https://www.reuters.com/article/us-usa-immigration-prosecutions/concerns-over-u-s-court-backlog-grow-with-rising-border-prosecutions-idUSKBN1IA310',
 'https://www.reuters.com/article/us-iran-nuclear-putin/russias-putin-deeply-concerned-at-usa-leaving-iran-deal-ria-idUSKBN1IA1NL',
 'https://www.reuters.com/article/us-television-roseanne/trump-sees-media-bias-in-handling-of-roseanne-cancellation-idUSKCN1IV10L',
 'https://www.reuters.com/article/us-northkorea-missiles/three-americans-freed-by-north-korea-head-home-thank-trump-idUSKBN1IA08I',
 'https://www.reuters.com/article/us-usa-trump-jackson/pentagon-watchdog-opens-probe-of-white-house-physician-ronny-jackson-idUSKCN1J02VZ',
 'https://www.reuters.com/article/us-iowa-abortion/iowa-passes-fetal-heartbeat-abortion-ban-most-restrictive-in-u-s-idUSKBN1I3257',
 'https://www.reuters.com/article/us-iran-nuclear-usa-royce/key-u-s-republican-says-u-s-should-stay-in-strictly-enforce-iran-deal-idUSKBN1I91TK',
 'https://www.reuters.com/article/us-usa-trump-haspel-interrogation/haspel-says-would-never-ever-resume-cia-harsh-interrogations-idUSKBN1IA2E7',
 'https://www.reuters.com/article/us-usa-municipals-budgets/u-s-states-2019-budgets-improve-but-long-term-stress-persists-idUSKBN1I24BS',
 'https://www.reuters.com/article/us-usa-energy-diplomacy/trump-pick-for-state-department-energy-job-approved-by-senate-panel-idUSKCN1IH2TC',
 'https://www.reuters.com/article/us-usa-congress-banks/house-votes-next-tuesday-on-bill-easing-post-crisis-bank-rules-sources-idUSKCN1IG36U',
 'https://www.reuters.com/article/us-usa-trump-russia-cohen/u-s-investigators-logged-trump-lawyers-phone-calls-nbc-idUSKBN1I42A2',
 'https://www.reuters.com/article/us-usa-trump-mueller/mueller-issues-grand-jury-subpoenas-to-trump-advisers-social-media-consultant-idUSKCN1IH2OB',
 'https://www.reuters.com/article/us-usa-epa-pruitt/trump-says-he-still-has-confidence-in-epa-chief-pruitt-idUSKBN1IC21A',
 'https://www.reuters.com/article/us-usa-trump-moon/trump-south-koreas-moon-to-meet-at-white-house-on-may-22-idUSKBN1I52M9',
 'https://www.reuters.com/article/us-usa-trump-russia-congress/bipartisan-u-s-election-probe-briefing-expected-in-june-white-house-idUSKCN1IP001',
 'https://www.reuters.com/article/us-missouri-governor/missouri-governor-stepping-down-amid-sex-fundraising-scandals-idUSKCN1IU2SE',
 'https://www.reuters.com/article/us-usa-guns-trump/trump-back-in-step-with-nra-after-doubts-over-parkland-shooting-idUSKBN1I50ZR',
 'https://www.reuters.com/article/us-usa-trade-mexico-midterms/republicans-in-tight-u-s-house-races-feel-heat-from-mexican-tariffs-idUSKCN1J22VP',
 'https://www.reuters.com/article/us-usa-election/democratic-hopes-for-house-control-buoyed-by-voting-results-idUSKCN1J228O',
 'https://www.reuters.com/article/us-iran-nuclear-russia-lavrov/moscow-says-remaining-sides-working-to-find-ways-to-preserve-iran-deal-idUSKBN1IB1FT',
 'https://www.reuters.com/article/us-usa-senate-mcwilliams/u-s-senate-confirms-former-banker-mcwilliams-to-lead-fdic-idUSKCN1IP30S',
 'https://www.reuters.com/article/us-usa-southkorea-harris/trump-nominates-pacific-commander-harris-as-u-s-ambassador-to-seoul-idUSKCN1IJ2RB',
 'https://www.reuters.com/article/us-usa-court-abortion/supreme-court-rejects-challenge-to-strict-arkansas-abortion-law-idUSKCN1IU1PH',
 'https://www.reuters.com/article/us-usa-whitehouse-mccain/mccains-daughter-slams-white-house-aides-hes-dying-comments-idUSKBN1IC1ZM',
 'https://www.reuters.com/article/us-illinois-crime-politics/ex-illinois-congressman-sentenced-to-prison-on-tax-charges-idUSKBN1IB305',
 'https://www.reuters.com/article/us-cuba-economy-un/u-s-trade-embargo-has-cost-cuba-130-billion-u-n-says-idUSKBN1IA00T',
 'https://www.reuters.com/article/us-iran-nuclear-students/students-protest-outside-former-u-s-embassy-in-tehran-fars-news-idUSKBN1IA27T',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-china-fbi-idUSKCN1IM2F6',
 'https://www.reuters.com/article/us-usa-trump-russia-justice/democrats-urge-trump-to-withdraw-justice-department-nominee-tied-to-russian-bank-idUSKBN1IA39M',
 'https://www.reuters.com/article/us-g7-summit/expect-disagreements-over-tariffs-at-g7-summit-canada-official-idUSKCN1J12E4',
 'https://www.reuters.com/article/us-usa-trump-wall/trump-and-mexican-president-spar-over-border-wall-again-idUSKCN1IV033',
 'https://www.reuters.com/article/us-usa-trump-russia-meeting/justice-department-expands-2016-probe-into-alleged-russia-collusion-idUSKCN1IM2AS',
 'https://www.reuters.com/article/us-iran-nuclear-usa/trump-has-all-but-decided-to-withdraw-from-iran-nuclear-deal-sources-idUSKBN1I331R',
 'https://www.reuters.com/article/us-usa-trade-koch/free-trade-puts-republican-megadonors-on-collision-course-with-trump-idUSKCN1J02C0',
 'https://www.reuters.com/article/us-usa-healthcare-pricing/president-trump-wants-to-go-further-on-drug-prices-hhs-secretary-idUSKBN1I327O',
 'https://www.reuters.com/article/us-illinois-execution/illinois-proposes-reinstating-death-penalty-for-mass-murder-police-killings-idUSKCN1IF33A',
 'https://www.reuters.com/article/us-usa-trump-russia/republican-house-speaker-says-trump-shouldnt-pardon-himself-idUSKCN1J21WR',
 'https://www.reuters.com/article/us-northkorea-usa-pence/trump-willing-to-walk-away-from-north-korea-summit-pence-idUSKCN1IM2CB',
 'https://www.reuters.com/article/us-usa-drones-security/u-s-officials-warn-congress-on-risks-of-drones-seek-new-powers-idUSKCN1J214S',
 'https://www.reuters.com/article/us-usa-russia-g20/russias-lavrov-says-may-meet-u-s-s-pompeo-at-g20-in-argentina-ifax-idUSKBN1I80QD',
 'https://www.reuters.com/article/us-usa-trump-daniels/trump-lawyer-giuliani-does-not-rule-out-payments-were-made-to-other-women-idUSKBN1I70RC',
 'https://www.reuters.com/article/us-people-georgehwbush/former-u-s-president-george-h-w-bush-taken-to-hospital-in-maine-idUSKCN1IS0PJ',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort/u-s-judge-says-mueller-should-not-have-unfettered-power-in-russia-probe-idUSKBN1I51WE',
 'https://www.reuters.com/article/us-new-york-corruption/ex-new-york-assembly-speaker-silver-found-guilty-in-second-corruption-trial-idUSKBN1IC2LV',
 'https://www.reuters.com/article/us-usa-congress-farmbill/senate-aims-to-finish-bipartisan-farm-bill-in-june-idUSKCN1IG320',
 'https://www.reuters.com/article/us-illinois-era/illinois-passes-equal-rights-amendment-more-than-three-decades-after-deadline-idUSKCN1IW0LB',
 'https://www.reuters.com/article/us-football-nfl-sea-den-trump-reax/players-react-to-trumps-comments-linebacker-marshall-calls-them-disgusting-idUSKCN1IP3SI',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-trade-deficit-china-buhari-idUSKBN1I24GU',
 'https://www.reuters.com/article/us-election-tech-advertising-lawsuit/washington-state-sues-facebook-google-over-election-ad-disclosure-idUSKCN1J030X',
 'https://www.reuters.com/article/us-facebook-privacy-congress/u-s-lawmakers-press-facebook-over-chinese-data-sharing-idUSKCN1J21OE',
 'https://www.reuters.com/article/us-usa-china-congress/u-s-lawmakers-plan-hearings-on-emboldened-china-idUSKCN1II2IM',
 'https://www.reuters.com/article/us-iran-nuclear-britain-business/britain-looking-at-impact-of-u-s-sanctions-on-iran-mays-spokesman-idUSKBN1IA1SA',
 'https://www.reuters.com/article/us-gymnastics-usa-congress/ex-officials-in-gymnastics-sex-abuse-scandal-subpoenaed-by-u-s-senate-idUSKCN1IV2KI',
 'https://www.reuters.com/article/us-usa-trump-autos-lawmakers/republicans-in-congress-slam-trump-probe-of-auto-imports-idUSKCN1IP35J',
 'https://www.reuters.com/article/us-usa-cfius-congress/foreign-investment-bill-targeting-china-heads-for-senate-panel-vote-idUSKBN1IC2MB',
 'https://www.reuters.com/article/us-usa-trump-melania/melania-trump-returns-to-white-house-after-kidney-procedure-idUSKCN1IK0KD',
 'https://www.reuters.com/article/us-usa-cyber-whitehouse/trump-scraps-cyber-czar-post-after-first-appointee-leaves-white-house-idUSKCN1IG3GG',
 'https://www.reuters.com/article/us-usa-china-zte/white-houses-kudlow-not-certain-what-u-s-will-do-on-chinas-zte-politico-idUSKCN1IG1W4',
 'https://www.reuters.com/article/us-usa-election-votingmachines/ahead-of-november-election-old-voting-machines-stir-concerns-among-u-s-officials-idUSKCN1IW16Z',
 'https://www.reuters.com/article/us-usa-cfius-congress/tighter-foreign-investment-oversight-put-in-u-s-senate-must-pass-bill-idUSKCN1IP3UF',
 'https://www.reuters.com/article/us-usa-trump-russia-lawsuit/trump-campaign-decries-lawsuit-claiming-russian-link-to-hacked-emails-idUSKCN1II32X',
 'https://www.reuters.com/article/us-northkorea-missiles-usa-southkorea/trump-says-release-of-detainees-by-north-korea-will-be-positive-for-u-s-north-korea-summit-south-korea-idUSKBN1IA2HB',
 'https://www.reuters.com/article/us-northkorea-missiles-usa-military/u-s-troops-in-south-korea-not-on-the-table-in-initial-north-korea-talks-idUSKBN1IA2M7',
 'https://www.reuters.com/article/us-iran-nuclear-intelligence/trumps-iran-move-reminds-some-of-run-up-to-iraq-war-idUSKBN1IB0HD',
 'https://www.reuters.com/article/us-usa-trump-russia-concord/russian-company-charged-in-mueller-probe-seeks-grand-jury-materials-idUSKCN1IF2YW',
 'https://www.reuters.com/article/us-iran-nuclear-rouhani-macron/europe-has-limited-opportunity-to-preserve-nuclear-deal-rouhani-tells-macron-idUSKBN1IA2TT',
 'https://www.reuters.com/article/us-northkorea-missiles-trump-pompeo/pompeo-on-way-to-pyongyang-says-has-no-commitment-on-u-s-prisoner-release-idUSKBN1I92XL',
 'https://www.reuters.com/article/us-missouri-governor/missouri-legislators-begin-weighing-impeachment-of-governor-idUSKCN1IJ14H',
 'https://www.reuters.com/article/us-nuclear-iran-trump-reaction/iranian-state-tv-says-trump-decision-is-illegal-idUSKBN1I92OS',
 'https://www.reuters.com/article/us-northkorea-missiles-usa-singapore/singapore-likeliest-option-for-trump-kim-summit-u-s-official-idUSKBN1IB06I',
 'https://www.reuters.com/article/us-usa-defense-congress/u-s-lawmakers-set-717-billion-defense-bill-with-eye-on-china-russia-turkey-idUSKBN1I52KW',
 'https://www.reuters.com/article/us-usa-trump-dodd-frank/trump-signs-bill-easing-u-s-bank-rules-into-law-idUSKCN1IP2WX',
 'https://www.reuters.com/article/us-usa-trade-china-trump/trump-says-there-is-no-deal-with-china-to-lift-ban-on-zte-corp-idUSKCN1IN2D3',
 'https://www.reuters.com/article/us-iran-nuclear-iraq/iraq-president-regrets-trump-decision-to-quit-iran-accord-idUSKBN1IA1LL',
 'https://www.reuters.com/article/us-iran-nuclear-johnson/uks-johnson-to-trump-iran-deal-has-weaknesses-but-dont-dump-it-idUSKBN1I80M3',
 'https://www.reuters.com/article/us-northkorea-missiles-usa-southkorea/u-s-south-korea-say-no-plans-to-change-bilateral-defense-posture-white-house-idUSKBN1I52P6',
 'https://www.reuters.com/article/us-usa-trump-russia-cohen/trump-lawyer-cohen-sought-1-million-from-qatar-in-late-2016-washington-post-idUSKCN1II061',
 'https://www.reuters.com/article/us-iran-nuclear-trump/trump-says-iran-will-negotiate-or-something-will-happen-idUSKBN1IA2NH',
 'https://www.reuters.com/article/us-usa-immigration-children/u-s-official-says-agency-did-not-lose-immigrant-children-idUSKCN1IU061',
 'https://www.reuters.com/article/us-missouri-governor/lawmakers-find-missouri-governor-lied-in-ethics-inquiry-about-donor-list-idUSKBN1I409E',
 'https://www.reuters.com/article/us-iran-nuclear-ryabkov/russias-ryabkov-urges-u-s-to-avoid-rash-steps-against-iran-tass-idUSKBN1I91OM',
 'https://www.reuters.com/article/us-usa-healthcare-drugpricing/u-s-to-consider-expanding-medicare-drug-price-negotiation-idUSKCN1IF1VI',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort-lawyer/lawyer-to-ex-trump-campaign-aide-manafort-taps-ethics-adviser-idUSKCN1J22LJ',
 'https://www.reuters.com/article/us-usa-election-republicans/mini-trump-candidates-battle-it-out-in-u-s-republican-primaries-idUSKBN1I70Q8',
 'https://www.reuters.com/article/us-missouri-governor/missouri-governor-offered-to-resign-if-charges-dropped-idUSKCN1IV11Y',
 'https://www.reuters.com/article/us-usa-trump-congress/trump-says-wants-a-government-funding-deal-before-august-break-idUSKCN1ID0XG',
 'https://www.reuters.com/article/us-usa-immigration-children/u-s-says-it-will-separate-families-crossing-border-illegally-idUSKBN1I82AB',
 'https://www.reuters.com/article/us-iran-nuclear-speaker/trump-does-not-have-mental-capacity-to-deal-with-issues-iran-parliament-speaker-idUSKBN1IA0FT',
 'https://www.reuters.com/article/us-usa-epa-security/u-s-epa-chief-pruitt-asked-for-24-7-security-from-day-one-watchdog-idUSKCN1IF2ZN',
 'https://www.reuters.com/article/us-usa-court-nominees/trump-push-for-conservative-judges-intensifies-to-democrats-dismay-idUSKBN1I80WL',
 'https://www.reuters.com/article/us-usa-trump-russia-giuliani/giuliani-says-legal-battle-would-ensue-if-mueller-subpoenas-president-trump-abc-idUSKCN1IZ00Q',
 'https://www.reuters.com/article/us-usa-ftc-equifax-smith/u-s-senators-oppose-trade-groups-lawyer-as-consumer-watchdog-idUSKCN1IF2T7',
 'https://www.reuters.com/article/us-usa-immigration-trump-wall/trump-will-seek-full-funding-soon-for-his-border-wall-idUSKCN1IH2XC',
 'https://www.reuters.com/article/us-g7-summit-usa/trump-to-have-meetings-with-frances-macron-canadas-trudeau-white-house-idUSKCN1J22DN',
 'https://www.reuters.com/article/us-usa-internet/senate-approves-bill-in-bid-to-retain-u-s-net-neutrality-idUSKCN1IH2DS',
 'https://www.reuters.com/article/us-nuclear-iran-araghchi/iran-says-will-react-to-trumps-decision-based-on-national-interests-irna-idUSKBN1I929C',
 'https://www.reuters.com/article/us-usa-trump-cohen/cohen-attorney-assails-stormy-daniels-lawyer-judge-sets-deadline-for-document-review-idUSKCN1IV1BB',
 'https://www.reuters.com/article/us-usa-myanmar-congress/house-backs-measure-to-clamp-down-on-myanmar-over-rohingya-rights-idUSKCN1IO3D8',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort/trump-campaign-aide-manafort-sued-by-bankruptcy-trustee-over-california-property-deal-idUSKBN1I22PQ',
 'https://www.reuters.com/article/us-nuclear-iran-irgc/revolutionary-guard-commander-says-iran-not-afraid-of-u-s-military-attack-fars-idUSKBN1I91VK',
 'https://www.reuters.com/article/us-usa-tillerson/tillerson-warns-of-u-s-ethical-crisis-in-apparent-swipe-at-trump-idUSKCN1II04B',
 'https://www.reuters.com/article/us-iran-nuclear-un/u-n-chief-warns-against-scrapping-iran-nuclear-deal-idUSKBN1I40H1',
 'https://www.reuters.com/article/us-iran-nuclear-germany-scholz/germany-aims-to-shield-firms-after-u-s-withdrawal-from-iran-deal-idUSKBN1IA258',
 'https://www.reuters.com/article/us-iran-nuclear-britain-diplomat/britain-deeply-pessimistic-ahead-of-trumps-iran-announcement-senior-uk-diplomat-idUSKBN1I91TS',
 'https://www.reuters.com/article/us-northkorea-usa-brazil/u-s-vice-president-pence-postpones-brazil-trip-as-north-korea-talks-loom-idUSKBN1I41QK',
 'https://www.reuters.com/article/us-usa-defense-china/mattis-says-u-s-to-continue-operations-in-south-china-sea-idUSKCN1IU2RB',
 'https://www.reuters.com/article/us-northkorea-missiles-prisoners-southko/south-korea-says-release-of-u-s-prisoners-positive-for-upcoming-trump-kim-summit-idUSKBN1IA1XJ',
 'https://www.reuters.com/article/us-usa-trump-russia/u-s-judge-refuses-to-dismiss-ex-trump-aide-manaforts-criminal-case-idUSKCN1IG3A5',
 'https://www.reuters.com/article/us-usa-trump-mueller-subpoena-exclusive/exclusive-special-counsel-subpoenas-another-stone-aide-in-russia-probe-sources-idUSKCN1IJ2MV',
 'https://www.reuters.com/article/us-iran-nuclear-options/trumps-options-on-iran-nuclear-deal-idUSKBN1I901J',
 'https://www.reuters.com/article/us-usa-immigration-caravan/half-of-caravan-asylum-seekers-in-u-s-sessions-puts-judges-on-border-idUSKBN1I30ID',
 'https://www.reuters.com/article/us-usa-trump-russia-lawyers/security-clearance-for-russia-probe-may-be-hard-for-giuliani-legal-experts-idUSKBN1I6008',
 'https://www.reuters.com/article/us-usa-immigration-texas/texas-sues-trump-administration-to-end-dreamers-program-idUSKBN1I24FN',
 'https://www.reuters.com/article/us-iran-nuclear-gulf-reaction/gulf-arab-allies-hail-triumph-after-u-s-quits-iran-deal-idUSKBN1I93CU',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort/trial-for-ex-trump-aide-manafort-pushed-back-to-july-24-idUSKCN1IQ2LZ',
 'https://www.reuters.com/article/us-usa-trump-russia-lawyers/trumps-lawyer-says-will-fight-russia-probe-subpoena-report-idUSKCN1IY0U9',
 'https://www.reuters.com/article/us-usa-trump-tax-aide/senior-tax-aide-to-leave-white-house-join-bank-lobbying-group-idUSKCN1J032W',
 'https://www.reuters.com/article/us-northkorea-usa-singapore-whitehouse/trumps-summit-with-north-koreas-kim-to-be-held-at-sentosa-island-hotel-white-house-idUSKCN1J129X',
 'https://www.reuters.com/article/us-usa-trump-disclosure/trump-reimbursed-attorney-who-paid-porn-star-stormy-daniels-disclosure-idUSKCN1IH2JC',
 'https://www.reuters.com/article/us-milken-conference-mccarthy/house-may-vote-on-dodd-frank-changes-in-may-majority-leader-idUSKBN1I126X',
 'https://www.reuters.com/article/us-usa-congress-chaplain/congressional-chaplain-can-stay-in-job-house-speaker-idUSKBN1I42T4',
 'https://www.reuters.com/article/us-usa-congress-recess/u-s-senate-leader-cancels-most-of-august-recess-idUSKCN1J12I7',
 'https://www.reuters.com/article/us-usa-environment-trump/u-s-conservationists-sue-trump-administration-over-migratory-bird-policy-idUSKCN1IP3VV',
 'https://www.reuters.com/article/us-usa-trump-haspel-senate/records-on-cia-nominee-will-not-be-made-public-key-u-s-lawmaker-idUSKBN1I92OF',
 'https://www.reuters.com/article/us-minnesota-attorney-general-ellison/congressman-keith-ellison-to-run-for-attorney-general-in-minnesota-idUSKCN1J12UG',
 'https://www.reuters.com/article/us-usa-fiscal-republicans/trump-proposes-15-billion-spending-cuts-targets-childrens-health-program-idUSKBN1I829L',
 'https://www.reuters.com/article/us-usa-ftc-equifax-smith/u-s-credit-reporting-industry-lawyer-may-head-ftc-bureau-sources-idUSKBN1IC2JE',
 'https://www.reuters.com/article/us-usa-whitehouse-mccain/top-republican-says-white-house-should-condemn-aid-who-mocked-mccain-idUSKCN1ID0YJ',
 'https://www.reuters.com/article/us-trade-nafta/nafta-talks-resume-amid-fears-of-zombie-deal-idUSKBN1I80BK',
 'https://www.reuters.com/article/us-usa-trump-cohen-ukraine/ukraine-paid-trump-lawyer-cohen-to-arrange-white-house-talks-bbc-idUSKCN1IO2ZC',
 'https://www.reuters.com/article/us-usa-trump-jerusalem/trump-says-he-may-visit-jerusalem-for-u-s-embassy-opening-idUSKBN1I246P',
 'https://www.reuters.com/article/us-oklahoma-adoption/oklahoma-passes-adoption-bill-critics-say-is-biased-against-gay-couples-idUSKBN1I5018',
 'https://www.reuters.com/article/us-usa-cyber-new-york/new-york-launches-drills-to-thwart-election-hacking-idUSKCN1IV2WM',
 'https://www.reuters.com/article/us-usa-trump-mccain/mccain-in-new-memoir-chides-trump-for-undermining-u-s-values-idUSKBN1I42L4',
 'https://www.reuters.com/article/us-usa-biofuels/trump-administration-biofuels-deal-delayed-indefinitely-sources-idUSKCN1J204I',
 'https://www.reuters.com/article/us-usa-economy-visas/u-s-may-open-door-to-more-temporary-immigrant-workers-trump-aide-says-idUSKCN1IX4YB',
 'https://www.reuters.com/article/us-iran-nuclear-france/france-says-iran-deal-not-dead-macron-to-contact-rouhani-idUSKBN1IA0PO',
 'https://www.reuters.com/article/us-blackrock-fees/blackrock-may-keep-fees-despite-executives-u-s-campaign-donation-sec-idUSKCN1ID0X4',
 'https://www.reuters.com/article/us-iran-nuclear-pentagon/mattis-stresses-work-with-allies-on-iran-even-after-major-split-idUSKBN1IA29E',
 'https://www.reuters.com/article/us-usa-trump-haspel-whitehouse/trumps-cia-pick-100-percent-committed-to-confirmation-process-white-house-idUSKBN1I825Y',
 'https://www.reuters.com/article/us-usa-biofuels-whitehouse/white-house-expected-to-announce-compromise-on-biofuels-sources-idUSKCN1J001H',
 'https://www.reuters.com/article/us-iran-nuclear-russia-germany/russian-german-top-diplomats-to-discuss-iran-in-moscow-agencies-idUSKBN1IA10T',
 'https://www.reuters.com/article/us-usa-trade-china-sinopec-corp/chinas-sinopec-to-boost-u-s-crude-imports-to-all-time-high-sources-idUSKCN1IO1MJ',
 'https://www.reuters.com/article/us-northkorea-usa-white-house/white-house-prepared-for-north-korea-summit-to-take-place-june-12-spokeswoman-idUSKCN1IU2T7',
 'https://www.reuters.com/article/us-usa-trump-daniels/trump-says-campaign-funds-were-not-used-to-pay-adult-film-star-idUSKBN1I417I',
 'https://www.reuters.com/article/us-iowa-abortion/iowa-governor-signs-fetal-heartbeat-abortion-ban-into-law-idUSKBN1I52ID',
 'https://www.reuters.com/article/us-usa-trump-election/trump-jr-met-gulf-princes-emissary-in-2016-who-offered-campaign-help-idUSKCN1IK0S1',
 'https://www.reuters.com/article/us-usa-trump-apprentice-lawsuit/apprentice-contestants-lawsuit-against-trump-to-proceed-ny-judge-idUSKCN1J11VP',
 'https://www.reuters.com/article/us-usa-trump-wall-mexico/mexican-president-again-tells-trump-mexico-will-not-pay-for-wall-idUSKCN1IV04W',
 'https://www.reuters.com/article/us-usa-court-gerrymandering/democratic-voters-challenge-ohio-congressional-district-map-idUSKCN1IO2BX',
 'https://www.reuters.com/article/us-usa-epa-pruitt/epa-chief-pruitts-ethics-issues-have-raised-concerns-white-house-idUSKBN1IB33R',
 'https://www.reuters.com/article/us-northkorea-missiles-detainees-factbox/factbox-the-three-americans-imprisoned-by-north-korea-idUSKBN1IA24Q',
 'https://www.reuters.com/article/us-britain-usa/uk-says-foreign-minister-johnson-to-meet-u-s-vp-pence-discuss-iran-north-korea-idUSKBN1I60XK',
 'https://www.reuters.com/article/us-iran-nuclear-macron-call/macron-to-discuss-iran-with-merkel-and-may-ahead-of-trump-decision-elysee-idUSKBN1I92I1',
 'https://www.reuters.com/article/us-usa-house-autolending/u-s-house-overturns-rule-meant-to-curb-car-loan-bias-idUSKBN1IA01Z',
 'https://www.reuters.com/article/us-usa-trump-cohen-at-t/att-says-it-cooperated-with-russia-probe-special-counsel-in-cohen-case-idUSKBN1IA3J9',
 'https://www.reuters.com/article/us-northkorea-cyber-usa/u-s-warns-again-on-hacks-it-blames-on-north-korea-idUSKCN1IU2O0',
 'https://www.reuters.com/article/us-usa-trump-dodd-frank-factbox/factbox-winners-and-losers-from-u-s-banking-rule-rewrite-idUSKCN1IP2XO',
 'https://www.reuters.com/article/us-usa-justice-terwilliger/adviser-to-justice-depts-no-2-named-interim-u-s-attorney-in-virginia-idUSKCN1IP32L',
 'https://www.reuters.com/article/us-usa-congress-environment/republican-lawmakers-probe-environmental-groups-overseas-work-idUSKCN1J12ZB',
 'https://www.reuters.com/article/us-iran-nuclear-obama/obama-calls-trumps-decision-on-iran-nuclear-deal-misguided-idUSKBN1I92ZX',
 'https://www.reuters.com/article/us-usa-trump-russia-interview/trump-lawyer-any-mueller-trump-interview-to-be-limited-washington-post-idUSKBN1I32JP',
 'https://www.reuters.com/article/us-g7-summit-russia/g7-to-uphold-russia-sanctions-senior-eu-official-idUSKCN1J12OM',
 'https://www.reuters.com/article/us-usa-immigration/top-trump-aide-says-protected-immigrants-need-path-to-citizenship-idUSKBN1IC1J6',
 'https://www.reuters.com/article/us-usa-fiscal-republicans/democrats-say-republicans-15-billion-spending-cut-request-hypocritical-idUSKBN1I9319',
 'https://www.reuters.com/article/us-usa-epa-pruitt/epa-chief-tells-u-s-lawmakers-he-has-fund-to-fight-ethics-complaints-idUSKCN1IH1AT',
 'https://www.reuters.com/article/us-usa-trump-twitter/u-s-appeals-against-ruling-that-trump-could-not-block-twitter-followers-idUSKCN1J1078',
 'https://www.reuters.com/article/us-usa-trump-apprentice-lawsuit/trump-says-immune-from-apprentice-contestant-lawsuit-seeks-delay-idUSKCN1IO1LT',
 'https://www.reuters.com/article/us-usa-trump-daniels/daniels-attorney-questions-trump-lawyer-dealings-firms-defend-payments-idUSKBN1IA2SA',
 'https://www.reuters.com/article/us-milken-conference-taxes/benefit-of-trump-tax-cuts-overshadowed-by-technology-and-misplaced-policies-milken-conference-speakers-idUSKBN1I12AZ',
 'https://www.reuters.com/article/us-iran-nuclear-diplomacy/pompeo-to-press-allies-on-iran-after-moves-on-north-korea-u-s-officials-idUSKBN1IB0EP',
 'https://www.reuters.com/article/us-usa-ftc/democrats-on-ftc-vote-no-on-consumer-protection-appointee-idUSKCN1IH36K',
 'https://www.reuters.com/article/us-iran-nuclear-deal-factbox/factbox-a-year-from-the-bomb-iran-deals-nuclear-restrictions-idUSKBN1I91VC',
 'https://www.reuters.com/article/us-gymnastics-usa-congress/ex-michigan-state-president-apologizes-in-gymnastics-sex-abuse-scandal-idUSKCN1J116C',
 'https://www.reuters.com/article/us-iran-nuclear-turkey/turkeys-erdogan-says-u-s-will-be-loser-in-quitting-iran-deal-state-media-idUSKBN1IA0U0',
 'https://www.reuters.com/article/us-usa-trump-russia-kremlin/kremlin-says-muellers-russia-investigation-is-pointless-idUSKCN1IU10O',
 'https://www.reuters.com/article/us-usa-puertorico-statehood/u-s-house-committee-chair-supports-puerto-rico-statehood-idUSKBN1I52FZ',
 'https://www.reuters.com/article/us-usa-trade-senate/u-s-lawmakers-seek-to-block-trump-on-tariffs-idUSKCN1J127G',
 'https://www.reuters.com/article/us-usa-trump-cohen/hearing-delayed-in-trump-lawyer-michael-cohens-new-york-court-case-idUSKCN1IO2JD',
 'https://www.reuters.com/article/us-iran-nuclear-jordan-germany/jordans-foreign-minister-sees-arms-race-if-iran-nuclear-deal-ends-idUSKBN1I91FC',
 'https://www.reuters.com/article/us-usa-trump-russia/trump-suggests-fbi-may-have-infiltrated-his-campaign-idUSKCN1IJ2I7',
 'https://www.reuters.com/article/us-usa-comey/comey-says-mueller-should-get-open-ended-interview-with-trump-idUSKBN1I22M4',
 'https://www.reuters.com/article/us-usa-trump-haspel/democrats-seek-more-records-on-trumps-choice-to-head-cia-idUSKBN1I8184',
 'https://www.reuters.com/article/us-northkorea-usa-prisoners-toll/mind-games-north-korean-detention-may-have-scarred-u-s-prisoners-idUSKBN1IA3DL',
 'https://www.reuters.com/article/us-usa-trump-russia-giuliani/stormy-daniels-payment-did-not-violate-campaign-laws-trump-lawyer-giuliani-idUSKBN1I52BH',
 'https://www.reuters.com/article/us-iran-nuclear-moussavi/iran-army-chief-says-the-worst-thing-the-nuclear-deal-did-was-give-u-s-legitimacy-idUSKBN1IA0MT',
 'https://www.reuters.com/article/us-nuclear-iran-jahangiri/iran-says-ready-for-any-scenario-if-trump-exits-nuclear-deal-tasnim-news-idUSKBN1I918F',
 'https://www.reuters.com/article/us-usa-house-banks/congress-eases-post-crisis-bank-rules-in-victory-for-trump-idUSKCN1IN316',
 'https://www.reuters.com/article/us-iran-nuclear-france-macron/frances-macron-calls-for-broader-iran-nuclear-deal-idUSKBN1IA2VS',
 'https://www.reuters.com/article/us-iran-nuclear-reaction/iran-says-trumps-abandoning-of-nuclear-deal-is-a-diplomatic-show-tv-idUSKBN1IA0JQ',
 'https://www.reuters.com/article/us-illinois-budget/bipartisan-fy-2019-budget-breezes-through-illinois-senate-idUSKCN1IW0AM',
 'https://www.reuters.com/article/us-usa-trade-zte-congress/congress-has-few-options-to-stop-trump-from-saving-chinas-zte-idUSKCN1J22WQ',
 'https://www.reuters.com/article/us-usa-trump-haspel/trumps-cia-nominee-sought-to-withdraw-over-interrogation-role-idUSKBN1I70RR',
 'https://www.reuters.com/article/us-missouri-governor/prosecutors-dismiss-criminal-charge-against-missouri-governor-idUSKCN1IF31Y',
 'https://www.reuters.com/article/us-iran-nuclear-congress-calls/u-s-withdrawing-from-iran-deal-with-window-before-reimposing-sanctions-sources-idUSKBN1I92JZ',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-lou-barletta-deb-fischer-gina-haspel-idUSKCN1II01C',
 'https://www.reuters.com/article/us-usa-china-zte-house/in-bipartisan-effort-two-u-s-lawmakers-ask-trump-to-be-tough-on-zte-idUSKCN1IN2P6',
 'https://www.reuters.com/article/us-usa-trump-cohen/michael-cohen-seeks-to-keep-stormy-daniels-lawyer-out-of-n-y-case-idUSKCN1IJ2WH',
 'https://www.reuters.com/article/us-usa-election/blankenship-loses-bitter-republican-senate-fight-in-west-virginia-idUSKBN1I913Q',
 'https://www.reuters.com/article/us-usa-trump-russia/pressure-builds-on-attorney-general-sessions-as-trump-pours-on-blame-idUSKCN1J11R3',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-healthcare-att-time-warner-idUSKBN1ID005',
 'https://www.reuters.com/article/us-iran-nuclear-russia-deal/russia-says-will-cooperate-with-iran-on-nuclear-deal-related-issues-idUSKBN1IB1YW',
 'https://www.reuters.com/article/us-usa-trump-tweet/trump-on-twitter-mitch-mcconnell-john-cox-melania-trump-idUSKCN1J21VF',
 'https://www.reuters.com/article/us-iran-nuclear-macron/macron-trump-discussed-peace-middle-east-stability-on-tuesday-office-idUSKBN1I9235',
 'https://www.reuters.com/article/us-iran-nuclear-kremlin/kremlin-says-any-u-s-withdrawal-from-iran-deal-may-have-negative-consequences-idUSKBN1I912M',
 'https://www.reuters.com/article/us-northkorea-usa-japan-abductee/japanese-woman-hopes-trump-kim-summit-will-bring-news-of-missing-twin-idUSKCN1J2023',
 'https://www.reuters.com/article/us-autos-emissions/major-automakers-urge-trump-not-to-freeze-fuel-economy-targets-idUSKBN1I821P',
 'https://www.reuters.com/article/us-people-schneiderman/new-york-state-attorney-general-resigns-after-report-he-abused-women-idUSKBN1I9049',
 'https://www.reuters.com/article/us-usa-trump-comey/ex-fbi-official-mccabe-gives-memo-on-comey-firing-to-mueller-new-york-times-idUSKCN1IW054',
 'https://www.reuters.com/article/us-usa-australia-corker/senator-corker-turns-down-trumps-offer-to-be-ambassador-to-australia-idUSKCN1IM2FT',
 'https://www.reuters.com/article/us-usa-trump-drugpricing/trump-says-drug-companies-to-announce-massive-price-cuts-soon-idUSKCN1IV2B2',
 'https://www.reuters.com/article/us-iran-nuclear-demands/iran-will-not-accept-eu-demands-beyond-nuclear-deal-iranian-official-idUSKBN1I91OE',
 'https://www.reuters.com/article/us-northkorea-missiles-trump-pompeo-arri/u-s-secretary-of-state-pompeo-arrives-in-pyongyang-u-s-pool-report-idUSKBN1IA02Z',
 'https://www.reuters.com/article/us-nuclear-iran-larijani/iran-hardline-official-says-tehran-should-leave-nuclear-deal-if-u-s-drops-it-tasnim-idUSKBN1I91HF',
 'https://www.reuters.com/article/us-usa-immigration-congress/u-s-house-starts-recess-as-immigration-battle-rages-idUSKCN1IP24T',
 'https://www.reuters.com/article/us-northkorea-usa-prisoners-un/u-n-rights-expert-urges-release-of-6-south-koreans-held-in-north-idUSKBN1IB1RD',
 'https://www.reuters.com/article/us-usa-airlines-regulation/trump-administration-opposes-requiring-reasonable-airline-baggage-fees-idUSKCN1IQ2XH',
 'https://www.reuters.com/article/us-usa-trump-nielsen/homeland-security-chief-nielsen-was-close-to-resigning-new-york-times-idUSKBN1IB36T',
 'https://www.reuters.com/article/us-iran-nuclear-supreme-leader/trump-speech-silly-and-superficial-irans-supreme-leader-says-idUSKBN1IA150',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-nafta-north-korea-china-idUSKBN1I4020',
 'https://www.reuters.com/article/us-usa-trump-security-adviser/trump-names-fears-as-homeland-security-adviser-white-house-idUSKCN1IX62X',
 'https://www.reuters.com/article/us-iran-nuclear-economy/iran-rial-plunges-to-new-low-after-trump-decides-to-leave-nuclear-deal-idUSKBN1IA1K1',
 'https://www.reuters.com/article/us-usa-internet/u-s-senate-to-vote-to-reinstate-open-internet-rules-idUSKBN1I9351',
 'https://www.reuters.com/article/us-usa-trade-china-trump/trump-china-soybean-tax-canadian-agricultural-products-trade-barriers-unacceptable-idUSKCN1J01LO',
 'https://www.reuters.com/article/us-iran-nuclear-spokesman/iran-has-drawn-up-plan-to-cope-with-u-s-withdrawal-from-nuclear-deal-government-spokesman-idUSKBN1IA2P2',
 'https://www.reuters.com/article/us-usa-trump-russia-memo/mueller-outlines-scope-of-russia-probe-in-court-filing-idUSKCN1II2EN',
 'https://www.reuters.com/article/us-iran-nuclear-oil/buyers-seek-u-s-waivers-to-buy-iranian-oil-amid-new-sanctions-idUSKBN1I93DT',
 'https://www.reuters.com/article/us-usa-comey-cyber/former-fbi-director-comey-says-agency-cannot-fight-foreign-propaganda-idUSKCN1IP3SN',
 'https://www.reuters.com/article/us-usa-court-search/supreme-court-puts-brakes-on-police-searches-of-rental-cars-idUSKCN1IF2K9',
 'https://www.reuters.com/article/us-northkorea-usa-whitehouse/white-house-optimistic-north-korea-summit-will-take-place-idUSKCN1IV2LY',
 'https://www.reuters.com/article/us-usa-trump-haspel/trump-cia-nominee-secures-key-democrats-vote-heads-for-confirmation-idUSKCN1IG2NU',
 'https://www.reuters.com/article/us-usa-pompeo/pompeo-on-first-day-at-state-department-promises-new-swagger-idUSKBN1I24AL',
 'https://www.reuters.com/article/us-iran-nuclear-usa-russia/moscow-says-should-not-be-any-influence-from-u-s-on-irans-partners-idUSKBN1IB1LA',
 'https://www.reuters.com/article/us-iran-nuclear-usa-pompeo/pompeo-says-confident-u-s-can-develop-common-approach-with-europeans-on-iran-idUSKCN1IN2TS',
 'https://www.reuters.com/article/us-usa-trump-haspel/u-s-senate-committee-to-vote-on-trump-cia-pick-on-wednesday-idUSKCN1IF250',
 'https://www.reuters.com/article/us-iran-nuclear-macron-response/frances-macron-says-will-keep-working-on-broader-iran-nuclear-deal-idUSKBN1I92OW',
 'https://www.reuters.com/article/us-usa-trump-doctor/doctor-says-trump-dictated-glowing-2015-health-report-cnn-idUSKBN1I3043',
 'https://www.reuters.com/article/us-usa-immigration-congress/u-s-house-members-near-forcing-dreamer-immigration-debate-idUSKCN1J12H0',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-kim-jong-un-isis-chuck-schumer-idUSKBN1IC04A',
 'https://www.reuters.com/article/us-usa-trump-russia-stone/u-s-grand-jury-questions-social-media-advisor-to-key-trump-supporter-idUSKCN1IX5FV',
 'https://www.reuters.com/article/us-northkorea-usa-ocongress/lawmakers-want-trump-to-report-on-north-korea-nuclear-program-idUSKCN1J222C',
 'https://www.reuters.com/article/us-iran-nuclear-hatami/iran-cant-be-threatened-militarily-defense-minister-idUSKBN1IA22C',
 'https://www.reuters.com/article/us-usa-trump-daniels-whitehouse/white-house-says-trump-did-not-initially-know-his-lawyer-paid-porn-star-idUSKBN1I42F1',
 'https://www.reuters.com/article/us-usa-trump-russia/trump-can-probably-pardon-himself-but-has-no-plan-to-giuliani-idUSKCN1IZ0KF',
 'https://www.reuters.com/article/us-usa-trump-russia-meeting/republicans-no-democrats-to-attend-meeting-on-fbi-campaign-surveillance-white-house-idUSKCN1IN2SH',
 'https://www.reuters.com/article/us-usa-trade-china/china-confirms-vice-premier-liu-he-will-go-to-u-s-to-discuss-trade-idUSKBN1IA0RS',
 'https://www.reuters.com/article/us-kentucky-election/teacher-defeats-rising-republican-star-in-kentuckys-state-house-race-media-idUSKCN1IO1HV',
 'https://www.reuters.com/article/us-usa-trump-haspel/trumps-cia-pick-promises-no-more-harsh-interrogation-program-idUSKBN1IA0H6',
 'https://www.reuters.com/article/us-usa-trump-pardon/trump-pardons-dinesh-dsouza-says-lifestyle-maven-stewart-may-be-next-idUSKCN1IW1TO',
 'https://www.reuters.com/article/us-iran-nuclear-japan/japan-says-will-closely-watch-impact-of-u-s-withdrawal-from-iran-deal-idUSKBN1IA080',
 'https://www.reuters.com/article/us-usa-immigration-privacy/lawsuit-against-u-s-border-searches-of-phones-can-move-forward-judge-idUSKBN1IB2LX',
 'https://www.reuters.com/article/us-usa-trade-china/trump-urges-a-new-structure-for-u-s-china-trade-deal-idUSKCN1IO1OB',
 'https://www.reuters.com/article/us-iran-nuclear-india-reaction/india-calls-for-dialogue-to-resolve-iran-nuclear-accord-dispute-idUSKBN1IA1P8',
 'https://www.reuters.com/article/us-usa-election-west-virginia/trump-urges-west-virginia-to-vote-against-former-coal-exec-who-went-to-prison-idUSKBN1I8149',
 'https://www.reuters.com/article/us-usa-china-zte-pompeo/pompeo-says-no-final-decision-made-yet-on-chinas-zte-idUSKCN1IO2AB',
 'https://www.reuters.com/article/us-usa-abortion/trump-proposes-taking-funds-away-from-abortion-providers-idUSKCN1IJ268',
 'https://www.reuters.com/article/northkorea-usa-prisoners-family-int/family-of-detained-american-grateful-for-his-release-from-north-korea-idUSKBN1IA25A',
 'https://www.reuters.com/article/us-usa-tax-rubio/senator-rubio-says-u-s-workers-get-little-benefit-from-tax-reform-report-idUSKBN1I127T',
 'https://www.reuters.com/article/us-facebook-privacy-congress/facebook-confirms-data-sharing-with-chinese-companies-idUSKCN1J11TY',
 'https://www.reuters.com/article/us-usa-trump-emoluments/trump-claims-immunity-asks-court-to-toss-foreign-payments-suit-idUSKBN1I31Y6',
 'https://www.reuters.com/article/us-iran-nuclear-rouhani/trump-does-not-have-mental-capacity-to-deal-with-issues-iran-parliament-speaker-idUSKBN1I92T7',
 'https://www.reuters.com/article/us-usa-immigration-entrepreneurs/u-s-proposes-scrapping-program-aimed-at-attracting-foreign-entrepreneurs-idUSKCN1IQ2SX',
 'https://www.reuters.com/article/us-northkorea-usa-putin/putin-praises-brave-trump-over-planned-meeting-with-north-koreas-kim-idUSKCN1J1334',
 'https://www.reuters.com/article/us-northkorea-missiles-envoy/explainer-the-man-sent-by-north-korean-leader-to-u-s-for-high-level-talks-idUSKCN1IU25U',
 'https://www.reuters.com/article/us-usa-trump-haspel/senate-panel-advances-trump-nominee-haspel-for-head-of-cia-idUSKCN1IH1TU',
 'https://www.reuters.com/article/us-usa-whitehouse-mccain/trump-aide-who-mocked-mccain-has-left-white-house-job-idUSKCN1J132M',
 'https://www.reuters.com/article/us-usa-trump-russia-democrats/democratic-lawmakers-say-no-evidence-in-briefings-of-fbi-spy-in-trump-campaign-idUSKCN1IP3IQ',
 'https://www.reuters.com/article/us-usa-biofuels/white-house-sets-meeting-with-senators-on-biofuels-next-week-sources-idUSKBN1I329D',
 'https://www.reuters.com/article/us-usa-court-grassley/key-senator-urges-any-wavering-u-s-high-court-justice-to-retire-now-idUSKBN1IB298',
 'https://www.reuters.com/article/us-usa-election/democrats-beat-vote-quirk-to-challenge-republicans-in-california-idUSKCN1J116L',
 'https://www.reuters.com/article/us-usa-trump-cohen-companies/companies-detail-payments-to-trump-lawyer-daniels-attorney-says-theres-more-idUSKBN1IA3EJ',
 'https://www.reuters.com/article/us-usa-cfius-mattis/mattis-urges-anti-china-measure-to-be-included-in-u-s-defense-bill-idUSKBN1I827S',
 'https://www.reuters.com/article/us-northkorea-usa-prisoners-whitehouse/trump-sees-american-prisoners-release-as-positive-gesture-white-house-idUSKBN1IA26P',
 'https://www.reuters.com/article/us-usa-trump-russia-questions/trump-blasts-leak-of-questions-he-could-face-in-russia-probe-idUSKBN1I22QF',
 'https://www.reuters.com/article/us-iran-nuclear-trump-macron/trump-to-discuss-iran-with-frances-macron-early-on-tuesday-senior-white-house-official-idUSKBN1I91S2',
 'https://www.reuters.com/article/us-usa-trump-russia/senate-panel-reveals-details-from-trump-tower-meeting-probe-idUSKCN1IH1S9',
 'https://www.reuters.com/article/us-usa-biofuels-grassley/republican-senator-says-epa-chief-must-slow-refinery-waivers-or-resign-idUSKCN1IG2AE',
 'https://www.reuters.com/article/us-usa-immigration-congress-daca-ryan/speaker-paul-ryan-eyes-immigration-bill-before-november-elections-idUSKBN1IB2DM',
 'https://www.reuters.com/article/us-usa-trump-apprentice-lawsuit/trump-fails-to-halt-apprentice-contestants-defamation-lawsuit-idUSKCN1II2DB',
 'https://www.reuters.com/article/us-iran-nuclear-mood/fear-loathing-and-dismay-in-iran-as-trump-exits-nuclear-deal-idUSKBN1IA1FZ',
 'https://www.reuters.com/article/us-usa-house-autolending/trump-signs-congressional-resolution-overturning-auto-lending-rule-idUSKCN1IM25V',
 'https://www.reuters.com/article/us-usa-pentagon-missiles-ai-insight/deep-in-the-pentagon-a-secret-ai-program-to-find-hidden-nuclear-missiles-idUSKCN1J114J',
 'https://www.reuters.com/article/us-northkorea-missiles-trump/pompeo-arrives-in-north-korea-trump-cites-hope-for-detainees-idUSKBN1I92ON',
 'https://www.reuters.com/article/us-usa-trump-guantanamo/u-s-transfers-inmate-from-guantanamo-even-as-trump-hints-at-refilling-it-idUSKBN1I32WT',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort-exclusive/exclusive-manaforts-former-son-in-law-cuts-plea-deal-to-cooperate-with-government-sources-idUSKCN1II2YM',
 'https://www.reuters.com/article/us-usa-election-solar/clean-energy-sector-swings-republican-with-u-s-campaign-donations-idUSKBN1I31DZ',
 'https://www.reuters.com/article/us-usa-trump-russia-qatar/trump-fundraiser-launches-subpoena-blitz-in-qatar-legal-fight-sources-idUSKCN1IP0DW',
 'https://www.reuters.com/article/us-nuclear-iran-sedighi/iranian-cleric-supreme-leader-predicted-nuclear-deal-would-fail-idUSKBN1I91FY',
 'https://www.reuters.com/article/us-usa-whitehouse-mccain/white-house-official-mocked-dying-senator-mccain-media-idUSKBN1IC05I',
 'https://www.reuters.com/article/us-iran-nuclear-reaction-egypt/arabs-must-have-say-in-any-new-iran-nuclear-deal-egypt-says-idUSKBN1IA1L9',
 'https://www.reuters.com/article/us-usa-election-taxcuts-insight/republicans-in-key-election-races-turn-down-volume-on-trumps-tax-cuts-idUSKBN1I80XB',
 'https://www.reuters.com/article/us-northkorea-missiles-usa/u-s-says-it-is-committed-to-working-with-north-korea-to-achieve-peace-idUSKBN1IA0NB',
 'https://www.reuters.com/article/us-usa-congress-farm-bill/farm-bill-to-get-second-vote-in-u-s-house-in-june-roll-call-idUSKCN1IN06I',
 'https://www.reuters.com/article/us-usa-election/key-u-s-house-battleground-forged-in-pennsylvania-idUSKCN1IG1BL',
 'https://www.reuters.com/article/us-usa-cfius-congress/republican-senators-president-to-discuss-anti-china-measure-at-white-house-idUSKCN1J12Q5',
 'https://www.reuters.com/article/us-usa-justice-cia/ex-cia-contractor-pleads-guilty-to-retaining-classified-information-idUSKBN1IC251',
 'https://www.reuters.com/article/us-usa-trump-haspel-testimony/trumps-pick-for-cia-director-says-will-not-restart-detention-program-idUSKBN1IA017',
 'https://www.reuters.com/article/us-usa-court-baker-adoption/gay-adoption-fight-looms-after-supreme-courts-cake-ruling-idUSKCN1J02X1',
 'https://www.reuters.com/article/us-usa-trump-russia-cohen/trump-lawyer-cohens-business-partner-cooperating-with-prosecutors-ny-times-idUSKCN1IN35E',
 'https://www.reuters.com/article/us-iran-nuclear/europeans-work-to-save-iran-deal-and-business-after-trump-pulls-out-idUSKBN1I90D6',
 'https://www.reuters.com/article/us-usa-congress-misconduct/u-s-senate-approves-bill-to-address-capitol-hill-sexual-harassment-idUSKCN1IP3NX',
 'https://www.reuters.com/article/us-usa-court-trump-factbox/factbox-the-court-scorebox-for-trump-and-his-challengers-idUSKBN1I91AO',
 'https://www.reuters.com/article/us-iran-nucelar-france/france-says-iran-deal-not-perfect-but-a-source-of-peace-idUSKBN1I90IU',
 'https://www.reuters.com/article/us-autos-safety/senate-panel-delays-vote-to-approve-auto-safety-chief-idUSKCN1IM2DA',
 'https://www.reuters.com/article/us-iran-nuclear-jafari/iran-revolutionary-guards-chief-says-europeans-tied-to-u-s-idUSKBN1IA0Q7',
 'https://www.reuters.com/article/us-usa-rights-un/americas-poor-becoming-more-destitute-under-trump-u-n-expert-idUSKCN1IY0C3',
 'https://www.reuters.com/article/us-iran-nuclear-cheney-panetta/cheney-panetta-worry-about-consequences-of-iran-deal-withdrawal-idUSKBN1IB08E',
 'https://www.reuters.com/article/us-g7-summit-foreign-threats/g7-to-pledge-joint-defense-of-democracies-from-foreign-threats-eu-official-idUSKCN1J12NN',
 'https://www.reuters.com/article/us-usa-immigration/u-s-ends-practice-that-gave-some-immigrants-reprieves-from-deportation-idUSKCN1IJ00N',
 'https://www.reuters.com/article/us-usa-trump-guns/trump-administration-to-publish-proposed-rule-changes-for-gun-exports-official-idUSKCN1IN2S7',
 'https://www.reuters.com/article/us-usa-sec-clayton/sec-chair-to-stress-cyber-risk-in-congressional-budget-testimony-idUSKCN1J02QT',
 'https://www.reuters.com/article/us-iran-nuclear-britain-johnson/britain-tells-trump-spell-out-how-you-will-deal-with-iran-now-idUSKBN1IA1R0',
 'https://www.reuters.com/article/us-iran-nuclear-government-businesses/uk-firms-should-consider-implications-of-u-s-sanctions-on-iran-mays-spokesman-idUSKBN1IA2IE',
 'https://www.reuters.com/article/us-usa-trump-daniels-at-t/att-payments-to-trump-lawyer-more-than-reported-source-idUSKBN1IA2KK',
 'https://www.reuters.com/article/us-television-samanthabee/trump-calls-for-comedian-samantha-bees-firing-after-crude-ivanka-slur-idUSKCN1IX4SR',
 'https://www.reuters.com/article/us-usa-court-baker/u-s-supreme-court-backs-christian-baker-who-rebuffed-gay-couple-idUSKCN1J01WU',
 'https://www.reuters.com/article/us-northkorea-usa-detainees/trump-says-china-has-been-very-helpful-on-north-korea-idUSKBN1IA2LL',
 'https://www.reuters.com/article/us-iran-nuclear-eu-meeting/eu-iran-discussed-nuclear-deal-ahead-of-trump-announcement-german-official-idUSKBN1I91UP',
 'https://www.reuters.com/article/us-usa-defense-congress-turkey/u-s-senate-defense-bill-would-bar-turkey-from-buying-f-35-jets-idUSKCN1IP3Q8',
 'https://www.reuters.com/article/us-people-reid/ex-senate-democratic-leader-reid-has-surgery-for-pancreatic-tumor-family-idUSKCN1IF2OV',
 'https://www.reuters.com/article/us-g7-summit-northkorea/g7-to-call-on-north-korea-to-get-rid-of-nuclear-weapons-senior-eu-official-idUSKCN1J12MB',
 'https://www.reuters.com/article/us-usa-trump-workers/trump-eases-firing-of-federal-workers-cracks-down-on-unions-idUSKCN1IQ355',
 'https://www.reuters.com/article/us-usa-nato-mattis/in-europe-mattis-is-in-familiar-spot-calming-u-s-allies-idUSKCN1J213N',
 'https://www.reuters.com/article/us-iran-nuclear-rouhani/ahead-of-trump-decision-iran-says-it-seeks-constructive-relations-with-the-world-idUSKBN1I90OJ',
 'https://www.reuters.com/article/us-usa-trump-haspel/u-s-senate-confirms-haspel-to-be-first-woman-cia-director-idUSKCN1II2SV',
 'https://www.reuters.com/article/us-usa-defense-congress/u-s-senate-panel-targets-china-russia-in-massive-defense-bill-idUSKCN1IP3RZ',
 'https://www.reuters.com/article/us-usa-trump-russia-cohen/trump-lawyer-met-russian-oligarch-shortly-before-inauguration-source-idUSKCN1IQ2HX',
 'https://www.reuters.com/article/us-usa-china-senate/senators-urge-trump-to-take-hard-line-in-dealings-with-china-idUSKCN1IN2Z9',
 'https://www.reuters.com/article/us-usa-trump-kushner/trump-adviser-and-son-in-law-jared-kushner-gets-security-clearance-back-idUSKCN1IO3E5',
 'https://www.reuters.com/article/us-iran-nuclear-russia/russias-lavrov-says-moscow-committed-to-iran-nuclear-deal-interfax-idUSKBN1IA0Y2',
 'https://www.reuters.com/article/us-iran-nuclear-trump-announcement/trump-says-u-s-pulling-out-of-iran-nuclear-deal-idUSKBN1I92NJ',
 'https://www.reuters.com/article/us-usa-trump-russia/prodded-by-trump-fbi-to-look-into-complaint-about-its-2016-tactics-idUSKCN1IM229',
 'https://www.reuters.com/article/us-iran-nuclear-sanctions/u-s-warns-allies-against-financial-dealings-with-iran-idUSKCN1J12CB',
 'https://www.reuters.com/article/us-usa-congress-farmbill/farm-bill-fails-in-u-s-house-as-immigration-spat-roils-republican-party-idUSKCN1IJ27N',
 'https://www.reuters.com/article/us-usa-trade-china/u-s-chinese-officials-to-meet-friday-discuss-liu-visit-u-s-official-idUSKBN1IC06G',
 'https://www.reuters.com/article/us-nuclear-iran-shamkhani/iran-says-will-not-be-passive-if-trump-exits-nuclear-deal-fars-idUSKBN1I91RS',
 'https://www.reuters.com/article/us-usa-trump-giuliani/giuliani-says-muellers-investigators-trying-to-frame-trump-idUSKCN1J21WC',
 'https://www.reuters.com/article/us-iran-nuclear-sanctions-factbox/factbox-how-trump-is-reimposing-iran-sanctions-after-ditching-deal-idUSKBN1I93CI',
 'https://www.reuters.com/article/us-iran-nuclear-parliament/iranian-mps-say-tehran-must-react-fiercely-to-u-s-pressure-over-deal-tv-idUSKBN1I92F6',
 'https://www.reuters.com/article/us-northkorea-usa-prisoners/upbeat-trump-welcomes-u-s-prisoners-released-by-north-korea-idUSKBN1IB0A2',
 'https://www.reuters.com/article/us-roche-cohen/roche-says-has-had-no-contact-with-trump-lawyer-cohen-idUSKCN1II1TI',
 'https://www.reuters.com/article/us-usa-trump-russia-qatar/trump-fundraiser-expands-u-s-lawsuit-accusing-qatar-of-hacking-his-emails-idUSKCN1IP3IO',
 'https://www.reuters.com/article/us-iran-nuclear-germany/german-foreign-minister-russia-can-influence-iran-to-stick-to-nuclear-deal-idUSKBN1IB1ID',
 'https://www.reuters.com/article/us-usa-trump-biofuels/trump-biofuel-policy-overhaul-to-include-fewer-refinery-waivers-source-idUSKBN1IC263',
 'https://www.reuters.com/article/us-iran-nuclear-un/u-n-chief-calls-on-remaining-parties-to-abide-by-iran-deal-idUSKBN1I92VP',
 'https://www.reuters.com/article/us-usa-trump-russia-flake/trumps-spygate-is-a-diversion-tactic-senator-flake-idUSKCN1IS0OQ',
 'https://www.reuters.com/article/us-usa-trump-russia-democrats/congressional-briefings-on-russia-should-not-be-taking-place-pelosi-idUSKCN1IP2XX',
 'https://www.reuters.com/article/us-iran-nuclear-macron-denial/trump-did-not-inform-macron-of-plans-for-iran-deal-french-presidents-office-idUSKBN1I92CQ',
 'https://www.reuters.com/article/us-usa-trump-tweet-factbox/trump-on-twitter-republican-party-mike-pompeo-idUSKBN1IA3IR',
 'https://www.reuters.com/article/us-usa-trump-pardon-stewart/trump-says-he-may-pardon-martha-stewart-idUSKCN1IW2D6',
 'https://www.reuters.com/article/us-northkorea-missiles-usa-pompeo/as-trump-visits-state-department-pompeo-says-north-korea-must-denuclearize-idUSKBN1I3273',
 'https://www.reuters.com/article/us-usa-congress-farmbill-trump/trump-hopes-u-s-house-can-resolve-differences-on-farm-bill-white-house-idUSKCN1IJ2FH',
 'https://www.reuters.com/article/us-usa-trump-russia-senate/obama-administration-too-slow-to-probe-russian-meddling-in-2016-senate-sources-idUSKCN1IN31R',
 'https://www.reuters.com/article/us-usa-congress-welfare/u-s-house-panel-approves-work-requirement-for-welfare-idUSKCN1IP374',
 'https://www.reuters.com/article/us-usa-trump-russia-concord/lawyer-for-russian-company-says-muellers-office-slow-to-hand-over-evidence-idUSKCN1IH2VP',
 'https://www.reuters.com/article/us-gymnastics-usa-congress/head-of-usa-gymnastics-apologizes-to-sex-abuse-victims-idUSKCN1IO1A3',
 'https://www.reuters.com/article/us-usa-trump-haspel-mccain/mccain-says-he-opposes-trumps-cia-nominee-idUSKBN1IB034',
 'https://www.reuters.com/article/us-northkorea-usa-schumer/schumer-warns-trump-against-quick-bad-deal-with-north-korea-idUSKBN1IB26P',
 'https://www.reuters.com/article/us-northkorea-missiles-prisoners-pompeo/top-u-s-diplomat-says-planning-for-one-day-trump-kim-meeting-going-well-idUSKBN1IA283',
 'https://www.reuters.com/article/us-usa-trump-taxes/trump-says-he-will-propose-new-tax-cuts-prior-to-november-idUSKCN1IO01S',
 'https://www.reuters.com/article/us-iran-nuclear-usa-isolation/americas-anti-iran-push-may-get-harder-with-nuclear-deal-pullout-idUSKBN1IA0GJ',
 'https://www.reuters.com/article/us-iran-nuclear-britain/britains-may-will-work-with-allies-on-iran-nuclear-deal-spokesman-idUSKBN1I91HB',
 'https://www.reuters.com/article/us-usa-china-zte-congress/u-s-lawmakers-were-briefed-on-chinas-zte-senator-idUSKCN1IP2WD',
 'https://www.reuters.com/article/us-usa-cfius-congress/senate-house-panels-ok-bills-to-tighten-foreign-investment-oversight-idUSKCN1IN2TC',
 'https://www.reuters.com/article/us-usa-cyber-election-senate/u-s-senators-accuse-russia-of-campaign-against-2016-vote-idUSKBN1IA02V',
 'https://www.reuters.com/article/us-missouri-governor/missouri-lawmakers-to-weigh-possible-impeachment-of-governor-on-may-18-idUSKBN1I504X',
 'https://www.reuters.com/article/us-usa-epa-security/epa-chiefs-security-bill-soars-agency-cites-death-threats-idUSKCN1IQ2X3',
 'https://www.reuters.com/article/us-usa-guantanamo/pentagon-crafts-new-criteria-for-picking-inmates-for-guantanamo-idUSKBN1I32AQ',
 'https://www.reuters.com/article/us-usa-immigration-visas/u-s-adds-15000-visas-for-seasonal-non-farm-workers-idUSKCN1IQ2XY',
 'https://www.reuters.com/article/us-usa-oil-campaign/senate-democrats-want-trump-to-prod-opec-to-lower-oil-prices-idUSKCN1IO300',
 'https://www.reuters.com/article/us-usa-house-ryan-banking/house-to-take-up-dodd-frank-rewrite-soon-says-speaker-ryan-idUSKBN1I92I7',
 'https://www.reuters.com/article/us-northkorea-usa-prisoners-trump/trump-welcomes-back-americans-freed-by-north-korea-idUSKBN1IB0QE',
 'https://www.reuters.com/article/us-usa-trump-veterans/trump-to-nominate-wilkie-to-head-department-of-veterans-affairs-idUSKCN1IJ26A',
 'https://www.reuters.com/article/us-iran-nuclear-russia/russia-vows-to-deepen-ties-with-iran-despite-u-s-sanctions-idUSKBN1IB0ZI',
 'https://www.reuters.com/article/us-usa-trump-russia-giuliani/mueller-told-trump-team-he-would-not-indict-trump-giuliani-told-cnn-idUSKCN1IH32G',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort/manafort-attempted-to-tamper-with-potential-witnesses-u-s-special-counsel-idUSKCN1J1043',
 'https://www.reuters.com/article/us-people-georgehwbush/former-u-s-president-george-h-w-bush-released-from-hospital-spokesman-idUSKCN1J02DW',
 'https://www.reuters.com/article/us-usa-trump-daniels/giuliani-says-trump-repaid-130000-his-lawyer-spent-to-quiet-porn-star-idUSKBN1I405J',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort/ex-trump-aide-manafort-faces-u-s-hearing-over-alleged-witness-tampering-idUSKCN1J11YA',
 'https://www.reuters.com/article/us-usa-immigration-congress/house-speaker-ryan-seeks-to-head-off-republican-revolt-on-immigration-idUSKCN1IH22M',
 'https://www.reuters.com/article/us-iran-nuclear-iaea/iran-still-implementing-commitments-under-nuclear-deal-iaea-says-idUSKBN1IA1JV',
 'https://www.reuters.com/article/us-usa-trump-russia/giuliani-wants-limits-for-trump-interview-in-russia-probe-idUSKBN1I42VU',
 'https://www.reuters.com/article/us-northkorea-usa-prisoners/pompeo-returning-from-north-korea-with-three-u-s-detainees-trump-idUSKBN1IA1W0',
 'https://www.reuters.com/article/us-iran-nuclear-trump/trump-will-announce-decision-on-iran-nuclear-deal-on-tuesday-idUSKBN1I826G',
 'https://www.reuters.com/article/us-usa-court-nominee/democrats-press-trump-nominee-to-influential-appeals-court-idUSKBN1IA321',
 'https://www.reuters.com/article/us-nuclear-iran-zarif/irans-zarif-warns-the-u-s-against-leaving-nuclear-deal-irna-idUSKBN1I927O',
 'https://www.reuters.com/article/us-russia-economy-forum-usa/u-s-ambassador-skips-encounter-with-sanctioned-russian-tycoon-idUSKCN1IQ0Y1',
 'https://www.reuters.com/article/us-usa-trump-russia-congress/democrats-say-briefings-did-not-support-trumps-claim-of-fbi-spy-idUSKCN1IP1SH',
 'https://www.reuters.com/article/us-usa-housing-discrimination/trump-administration-to-reconsider-housing-bias-protections-idUSKBN1IB2Q6',
 'https://www.reuters.com/article/us-usa-trump-tweet/trump-on-twitter-russia-investigation-trade-china-idUSKCN1J02AS',
 'https://www.reuters.com/article/us-usa-trump-russia/trump-says-has-power-to-pardon-himself-critics-disagree-idUSKCN1J01L2',
 'https://www.reuters.com/article/us-iran-nuclear-germany-usa/germany-russian-foreign-ministers-call-for-iran-deal-to-be-upheld-idUSKBN1IB1MW',
 'https://www.reuters.com/article/us-television-john-mccain/with-gratitude-ailing-john-mccain-looks-back-in-hbo-documentary-idUSKCN1IP2VF',
 'https://www.reuters.com/article/us-usa-trump-haspel/white-house-campaigns-to-win-senate-confirmation-of-cia-nominee-idUSKBN1I3366',
 'https://www.reuters.com/article/us-usa-court-abortion-immigrant/u-s-high-court-throws-out-immigrant-teen-abortion-ruling-idUSKCN1J01RB',
 'https://www.reuters.com/article/us-usa-congress-farmbill/u-s-senate-leader-points-to-farm-bill-vote-around-july-4-idUSKCN1J12LV',
 'https://www.reuters.com/article/us-usa-fiscal-republicans-trump/trump-proposes-15-billion-spending-cuts-targets-childrens-health-program-idUSKBN1I82JS',
 'https://www.reuters.com/article/us-usa-trump-russia-justice/u-s-justice-department-asks-watchdog-to-check-for-political-motivations-in-fbi-russia-probe-idUSKCN1IL0VJ',
 'https://www.reuters.com/article/us-iran-nuclear-usa-britain/trump-may-condemn-iran-rocket-attacks-on-israel-white-house-idUSKBN1IC2KU',
 'https://www.reuters.com/article/us-usa-trump-daniels-novartis/swiss-prosecutors-will-not-pursue-novartis-over-trump-lawyer-payments-idUSKCN1J21KW',
 'https://www.reuters.com/article/us-usa-trump-russia-committee/key-senators-no-doubt-russia-sought-to-interfere-in-u-s-election-idUSKCN1IH2AX',
 'https://www.reuters.com/article/us-usa-epa-pruitt-mattress/epa-staffer-ran-errands-for-pruitt-looked-into-buying-trump-mattress-idUSKCN1J02VP',
 'https://www.reuters.com/article/us-iran-nuclear-pentagon-funding/pentagon-not-anticipating-additional-funding-after-withdrawal-from-nuclear-deal-idUSKBN1IA2M1',
 'https://www.reuters.com/article/us-iran-nuclear-iraq-ministry/iraqi-foreign-ministry-says-trumps-decision-on-iran-hasty-and-rash-idUSKBN1IA26F',
 'https://www.reuters.com/article/us-usa-security-nielsen/u-s-agency-seeks-new-authority-to-disable-threatening-drones-idUSKCN1IG33G',
 'https://www.reuters.com/article/us-usa-cyber-surveillance/spy-agency-nsa-triples-collection-of-u-s-phone-records-official-report-idUSKBN1I52FR',
 'https://www.reuters.com/article/us-iran-nuclear/trump-to-unveil-iran-decision-tuesday-europeans-move-his-way-idUSKBN1I8284',
 'https://www.reuters.com/article/us-iran-nuclear-europe/eu-cant-save-iran-nuclear-deal-after-u-s-move-senior-revolutionary-guard-idUSKBN1IB0X7',
 'https://www.reuters.com/article/us-usa-trump-russia-congress/republicans-no-democrats-invited-to-see-documents-on-u-s-election-probe-idUSKCN1IN2E9',
 'https://www.reuters.com/article/us-usa-trump-russia/trump-to-ask-justice-department-to-look-into-campaign-surveillance-claims-idUSKCN1IL0PQ',
 'https://www.reuters.com/article/usa-immigration-congress/some-u-s-house-republicans-see-progress-on-dreamer-immigration-deal-idUSKCN1II32N',
 'https://www.reuters.com/article/us-usa-trump-haspel-china/cia-nominee-u-s-must-do-more-vs-china-efforts-to-steal-technology-idUSKBN1IA2GD',
 'https://www.reuters.com/article/us-usa-firstlady/u-s-first-lady-melania-trump-to-skip-g7-north-korea-summit-idUSKCN1J001Z',
 'https://www.reuters.com/article/us-iran-nuclear-scenarios/what-could-iran-do-if-trump-pulls-out-of-nuclear-deal-idUSKBN1I903G',
 'https://www.reuters.com/article/us-usa-internet/senate-votes-wednesday-on-effort-to-reinstate-net-neutrality-rules-idUSKCN1IF26P',
 'https://www.reuters.com/article/us-usa-trump-twitter/trumps-blocking-of-critics-on-twitter-violates-constitution-u-s-judge-idUSKCN1IO2P2',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort-judge/u-s-judge-declines-to-dismiss-ex-trump-aides-false-statement-charges-idUSKCN1IQ2YR',
 'https://www.reuters.com/article/us-usa-trump-veteransaffairs/trump-considers-ex-congressman-now-lobbyist-for-veterans-post-idUSKBN1I31WU',
 'https://www.reuters.com/article/us-autos-emissions-whitehouse/trump-to-meet-with-automakers-to-discuss-u-s-fuel-rules-sources-idUSKBN1I32YS',
 'https://www.reuters.com/article/us-usa-election-security/u-s-officials-warn-congress-on-2018-election-hacking-threats-idUSKCN1IN25H',
 'https://www.reuters.com/article/us-iran-nuclear-diplomacy/europe-licks-wounds-as-saudi-arabia-and-israel-hail-trump-on-iran-idUSKBN1IA38C',
 'https://www.reuters.com/article/us-northkorea-missiles-trump/top-north-korea-envoy-to-hold-crucial-talks-in-u-s-about-summit-idUSKCN1IU17C',
 'https://www.reuters.com/article/us-iran-nuclear-usa-sanctions/u-s-preparing-to-impose-new-sanctions-on-iran-white-house-idUSKBN1IA37T',
 'https://www.reuters.com/article/us-usa-trump-drugpricing/trump-assails-high-drug-prices-avoids-direct-hit-on-industry-idUSKBN1IC2C0',
 'https://www.reuters.com/article/us-usa-immigration-honduras/trump-administration-moves-to-expel-some-57000-hondurans-idUSKBN1I52DW',
 'https://www.reuters.com/article/iran-nuclear-supreme-leader-int/trump-speech-silly-and-superficial-irans-supreme-leader-says-idUSKBN1IA154',
 'https://www.reuters.com/article/us-iran-nuclear-usa/pompeo-reaches-out-to-european-counterparts-amid-iran-tensions-idUSKCN1IF2JS',
 'https://www.reuters.com/article/us-northkorea-missiles-usa-rights/u-s-says-will-press-north-korea-on-human-rights-abuses-idUSKBN1I32RH',
 'https://www.reuters.com/article/us-northkorea-missiles-southkorea/south-korean-foreign-minister-to-strategize-with-pompeo-ahead-of-korea-summits-idUSKBN1IB074',
 'https://www.reuters.com/article/us-northkorea-usa-congress/senate-democrats-vow-to-buck-trump-on-north-korea-without-tough-deal-idUSKCN1J023C',
 'https://www.reuters.com/article/us-usa-trump-russia-manafort/judge-questions-ex-trump-campaign-chiefs-bid-to-suppress-evidence-idUSKCN1IO19F',
 'https://www.reuters.com/article/us-nuclear-iran-bagheri/iran-says-no-military-threat-frightens-it-irna-idUSKBN1I91DT',
 'https://www.reuters.com/article/us-usa-trump-russia-mueller/mueller-probe-spent-4-5-million-from-october-to-march-justice-department-idUSKCN1IW2XW',
 'https://www.reuters.com/article/us-pakistan-usa/u-s-diplomat-involved-in-fatal-accident-allowed-to-leave-pakistan-idUSKCN1IF2QH',
 'https://www.reuters.com/article/us-usa-election-primary-california/bumpy-road-for-california-democrats-targeting-republican-house-seats-idUSKCN1IX5NT',
 'https://www.reuters.com/article/us-usa-arms-saudi-emirates/congress-reviewing-sale-of-precision-munitions-to-saudis-uae-sources-idUSKCN1IO032',
 'https://www.reuters.com/article/us-iran-nuclear-whitehouse/white-house-denies-ny-times-report-of-u-s-withdrawal-from-iran-nuclear-deal-idUSKBN1I92G2',
 'https://www.reuters.com/article/us-northkorea-missiles-summit/trump-says-u-s-north-korea-summit-will-not-be-at-demilitarized-zone-idUSKBN1IA2N5',
 'https://www.reuters.com/article/us-northkorea-missiles-amnesty/north-koreas-kim-says-releases-three-american-detainees-upon-u-s-request-kcna-idUSKBN1IA3DS',
 'https://www.reuters.com/article/us-northkorea-missiles-mattis/mattis-reason-for-some-optimism-on-u-s-north-korea-talks-idUSKBN1IA2E0',
 'https://www.reuters.com/article/us-usa-trump/trump-threatens-aid-cut-to-countries-that-do-not-stop-ms-13-gang-migrants-idUSKCN1IO30Y',
 'https://www.reuters.com/article/us-usa-trump-daniels-korea-aerospace/south-koreas-kai-says-paid-firm-of-trumps-lawyer-150000-for-accounting-advice-idUSKBN1IA135',
 'https://www.reuters.com/article/us-iran-nuclear-decision/trump-tells-macron-u-s-to-pull-out-of-iran-deal-new-york-times-idUSKBN1I9282']
#Gets a unique set of links
links_ = list(set(links_))
#got functions
def get_rueters_article(url):
    #Sends request to url
    page = requests.get(url)
    html = page.text
    return html

def parse_rueters_article(html):
    #BeautifulSoup the page
    soup = BeautifulSoup(html, 'lxml')
    title = soup.find('h1', class_='headline_2zdFM').text
    body = soup.find('div', class_='body_1gnLA').text

    article = {
        'title': title,
        'body': body,
        'source': 'Reuters',
        'num_source': 2
    }

    return article

def get_parsed_article_from_link(url):
    #Runs parse article on each of the urls
    return parse_rueters_article(get_rueters_article(url))
#runs articles through phase 1
rueters_list_o_articles = []
rueters_problem_articles = []
for text in links_:
    try:
        art = get_parsed_article_from_link(text.encode())
        rueters_list_o_articles.append(art)

    except:
        print("Problem processing url " + text)
        problem = text
        rueters_problem_articles.append(problem)
    time.sleep(2)
#phase 2 of rejected articles
driver = webdriver.PhantomJS(service_args=['--ssl-protocol=any'])
for x in rueters_problem_articles:
    driver.get(x)
    time.sleep(3)
    try:
        soupy = BeautifulSoup(driver.page_source, 'lxml')
        title = soupy.find('h1', class_='headline_2zdFM').text
        sub_title = 'That percentage has barely budged since last y.'
        body = soupy.find('div', class_='body_1gnLA').text

        articley = {
            'title': title,
            'body': body,
            'source': 'Reuters',
            'num_source': 2
        }
        rueters_list_o_articles.append(articley)
    except:
        pass
#starts client in Mongodb
client = MongoClient()
biased_news = client.project5.biased_news
#creates event and loads articles into Mongodb
db = client.events
biased_news = db.biased_news
biased_news.insert_many(rueters_list_o_articles)
